Repository KiCad/kicad-footprints, pull requests merged in 2018-12, with the labels that each got.

#1014 Audio jack fix
  Connector_Audio.pretty/Jack_3.5mm_Ledino_KB3SPRS_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_Neutric_NMJ6HCD2_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_Neutrik_NMJ6HCD2_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_PJ31060-I_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_PJ320D_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_PJ320E_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical_CircularHoles.kicad_mod
  Connector_Audio.pretty/Jack_Horizontal.kicad_mod
Labels: Bug

#1125 name mounting pads of PTSM SMD connectors with `MP`
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-2-2,5-V-SMD_1x02_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-2-HV-2.5-SMD_1x02_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-3-2,5-V-SMD_1x03_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-3-HV-2.5-SMD_1x03_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-4-2,5-V-SMD_1x04_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-4-HV-2.5-SMD_1x04_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-5-2,5-V-SMD_1x05_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-5-HV-2.5-SMD_1x05_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-6-2,5-V-SMD_1x06_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-6-HV-2.5-SMD_1x06_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-7-2,5-V-SMD_1x07_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-7-HV-2.5-SMD_1x07_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-8-2,5-V-SMD_1x08_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-8-HV-2.5-SMD_1x08_P2.50mm_Vertical.kicad_mod
Labels: Enhancement, Pending reviewer

#1100 Add footprint for Bel S558-5999-T7-F
  Transformer_SMD.pretty/Transformer_Ethernet_Bel_S558-5999-T7-F.kicad_mod
Labels: Addition, Pending reviewer

#1097 Add Microchip QFN footprints
  Package_DFN_QFN.pretty/UQFN-16-1EP_4x4mm_P0.65mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-16-1EP_4x4mm_P0.65mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm_ThermalVias.kicad_mod
Labels: Addition

#1038 Add GCT USB4085 USB 2.0 Type-C receptacle
  Connector_USB.pretty/USB_C_Receptacle_GCT_USB4085.kicad_mod
Labels: Addition

#1116 coaxial connector sma molex 73251-2200 horziontal
  Connector_Coaxial.pretty/SMA_Molex_73251-2200_Horizontal.kicad_mod
Labels: Addition, Pending changes

#1123 Package_QFP: add LQFP-52_14x14mm_P1mm
  Package_QFP.pretty/LQFP-52_14x14mm_P1mm.kicad_mod
Labels: Addition, Pending reviewer

#628 Footprint for microSIM card from JAE
  Connector_Card.pretty/microSIM_JAE_SF53S006VCBR2000.kicad_mod
Labels: Question

#964 added Taiyo-Yuden_EYSGJNZWY
  RF_Module.pretty/Taiyo-Yuden_EYSGJNZWY.kicad_mod
Labels: Addition, Pending reviewer

#1099 Add Ublox SARA G3/U2 footprint
  RF_Module.pretty/ublox_SARA-G3_LGA-96.kicad_mod
Labels: Addition, Pending changes

#1112 OCXO OH300
  Oscillator.pretty/Oscillator_SMD_OCXO_ConnorWinfield_OH300.kicad_mod
Labels: Addition, Pending changes

#1147 Add CUI CPT-9019S
  Buzzer_Beeper.pretty/Buzzer_CUI_CPT-9019S-SMT.kicad_mod
Labels: Addition, Pending changes

#1129 Add WLP-4 0.73x0.73mm 0.35mm pitch
  Package_BGA.pretty/WLP-4_0.73x0.73mm_Layout2x2_P0.35mm_Ball0.22mm_Pad0.2mm_NSMD.kicad_mod
Labels: Addition, Pending reviewer

#1142 PSTM -1MP in SMD package names
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-2-2,5-V-SMD_1x02-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-2-HV-2.5-SMD_1x02-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-3-2,5-V-SMD_1x03-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-3-HV-2.5-SMD_1x03-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-4-2,5-V-SMD_1x04-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-4-HV-2.5-SMD_1x04-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-5-2,5-V-SMD_1x05-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-5-HV-2.5-SMD_1x05-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-6-2,5-V-SMD_1x06-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-6-HV-2.5-SMD_1x06-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-7-2,5-V-SMD_1x07-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-7-HV-2.5-SMD_1x07-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-8-2,5-V-SMD_1x08-1MP_P2.50mm_Vertical.kicad_mod
  TerminalBlock_Phoenix.pretty/TerminalBlock_Phoenix_PTSM-0,5-8-HV-2.5-SMD_1x08-1MP_P2.50mm_Vertical.kicad_mod
Labels: Enhancement, Pending reviewer

#1079 Lts 69xx
  Display_7Segment.pretty/LTS-69xx.kicad_mod
Labels: Enhancement, Pending reviewer

#1063 Create DFN-6-1EP_3x2mm_P0.5mm_EP1.65x1.35mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_3x2mm_P0.5mm_EP1.65x1.35mm.kicad_mod
Labels: Addition

#977 Added SOT-1123
  Package_TO_SOT_SMD.pretty/SOT-1123.kicad_mod
Labels: Addition, Pending changes

#371 Add Potentiometer_TT_P0915N
  Potentiometer_THT.pretty/Potentiometer_TT_P0915N.kicad_mod
Labels: Question

#1172 [Fix] fixes for remaining issues of sot-1123
  Package_TO_SOT_SMD.pretty/SOT-1123.kicad_mod
Labels: Bug

#1148 Mini-Circuits land-pattern PL-094
  Package_SO.pretty/Mini-Circuits_CD542_LandPatternPL-094.kicad_mod
Labels: Addition

#1150 Add Mini-Circuits land-pattern PL-225
  Package_SO.pretty/Mini-Circuits_MMM168_LandPatternPL-225.kicad_mod
Labels: Addition, Pending changes

#1137 Mini-Circuits land-pattern PL-049
  Package_SO.pretty/Mini-Circuits_YY161_LandPatternPL-049.kicad_mod
Labels: Addition

#1108 Morion ocxos MV267 and MV317
  Oscillator.pretty/Oscillator_OCXO_Morion_MV267.kicad_mod
  Oscillator.pretty/Oscillator_OCXO_Morion_MV317.kicad_mod
Labels: Addition, Pending changes

#1166 Added QFN-16, 3x3mm
  Package_DFN_QFN.pretty/QFN-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm.kicad_mod
Labels: Addition

#882 Finish #589: Mini-Circuits Filter Mounts FV1206 and variants
  Filter.pretty/Filter_Mini-Circuits_FV1206-1.kicad_mod
  Filter.pretty/Filter_Mini-Circuits_FV1206-4.kicad_mod
  Filter.pretty/Filter_Mini-Circuits_FV1206-5.kicad_mod
  Filter.pretty/Filter_Mini-Circuits_FV1206-6.kicad_mod
  Filter.pretty/Filter_Mini-Circuits_FV1206-7.kicad_mod
  Filter.pretty/Filter_Mini-Circuits_FV1206.kicad_mod
Labels: Addition, Pending changes

#1186 IPC conformal fiducials - update
  Fiducial.pretty/Fiducial_0.5mm_Mask1.5mm.kicad_mod
  Fiducial.pretty/Fiducial_0.5mm_Mask1mm.kicad_mod
  Fiducial.pretty/Fiducial_0.75mm_Mask1.5mm.kicad_mod
  Fiducial.pretty/Fiducial_0.75mm_Mask2.25mm.kicad_mod
  Fiducial.pretty/Fiducial_1.5mm_Mask3mm.kicad_mod
  Fiducial.pretty/Fiducial_1.5mm_Mask4.5mm.kicad_mod
  Fiducial.pretty/Fiducial_1mm_Mask2mm.kicad_mod
  Fiducial.pretty/Fiducial_1mm_Mask3mm.kicad_mod
  Obsolete/Fiducial/Fiducial_1mm_Dia_2.54mm_Outer_CopperBottom.kicad_mod
  Obsolete/Fiducial/Fiducial_1mm_Dia_2.54mm_Outer_CopperTop.kicad_mod
  Obsolete/Fiducial/Fiducial_Modern_CopperBottom.kicad_mod
  Obsolete/Fiducial/Fiducial_Modern_CopperTop.kicad_mod
  Obsolete/Fiducial/Fiducial_Modern_SilkscreenTop.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_CopperBottom_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_CopperBottom_Type2.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_CopperTop_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_CopperTop_Type2.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_SilkscreenTop_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_Small_SilkscreenTop_Type2.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_CopperBottom_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_CopperBottom_Type2.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_CopperTop_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_CopperTop_Type2.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_SilkscreenTop_Type1.kicad_mod
  Obsolete/Fiducial/Fiducial_classic_big_SilkscreenTop_Type2.kicad_mod
Labels: Enhancement, Pending reviewer

#1176 Replace existiong LQFP 32 and 36 with scripted variants
  Package_QFP.pretty/LQFP-32-1EP_5x5mm_P0.5mm_EP3.45x3.45mm.kicad_mod
  Package_QFP.pretty/LQFP-32_5x5mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-32_7x7mm_P0.8mm.kicad_mod
  Package_QFP.pretty/LQFP-36_7x7mm_P0.65mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1178 New MQFP 44 footprint for ad7722
  Package_QFP.pretty/MQFP-44_10x10mm_P0.8mm.kicad_mod
Labels: Addition, Pending reviewer

#1033 Add BGA-624_25x25_21.0x21.0mm_Pitch0.8mm
  Package_BGA.pretty/BGA-624_21.0x21.0mm_Layout25x25_P0.8mm.kicad_mod
Labels: Addition, Pending changes

#1190 Scripted versions of EQFP-144-1EP (Previosly LQFP)
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP6.61x5.615mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP6.61x5.615mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP7.2x6.35mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP7.2x6.35mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.7mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.7mm_ThermalVias.kicad_mod
  Package_QFP.pretty/LQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm.kicad_mod
  Package_QFP.pretty/LQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/LQFP-144-1EP_20x20mm_P0.5mm_EP6.61x6.61mm.kicad_mod
  Package_QFP.pretty/LQFP-144-1EP_20x20mm_P0.5mm_EP7.2x7.2mm.kicad_mod
  Package_QFP.pretty/LQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.93mm.kicad_mod
Labels: Bug, Enhancement, Pending reviewer

#1177 Newly scripted footprints for LQFP 44 and 48
  Package_QFP.pretty/LQFP-44_10x10mm_P0.8mm.kicad_mod
  Package_QFP.pretty/LQFP-48_7x7mm_P0.5mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1188 Scripted versions for LQFP-80 and LQFP-100
  Package_QFP.pretty/LQFP-100_14x14mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-80_10x10mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-80_12x12mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-80_14x14mm_P0.65mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1189 Scripted version of LQFP-128 footprints
  Package_QFP.pretty/LQFP-128_14x14mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-128_14x20mm_P0.5mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1192 Scripted version of LQFP-208 and LQFP-216
  Package_QFP.pretty/LQFP-208_28x28mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-216_24x24mm_P0.4mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1191 Scripted version for LQFP-144, 160 and 176
  Package_QFP.pretty/LQFP-144_20x20mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-160_24x24mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-176_20x20mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-176_24x24mm_P0.5mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1092 Pulls/hlk pm01
  Converter_ACDC.pretty/Converter_ACDC_HiLink_HLK-PMxx.kicad_mod
Labels: Addition, Pending changes

#1157 Connector_USB: Add Molex 105133-0031
  Connector_USB.pretty/USB_Micro-B_Molex-105133-0031.kicad_mod
Labels: Addition

#1200 Converter_ACDC: Add RAC05 series
  Converter_ACDC.pretty/Converter_ACDC_RECOM_RAC05-xxSK_THT.kicad_mod
Labels: Addition

#1207 Scripted qfn for SX1272
  Package_DFN_QFN.pretty/QFN-28-1EP_6x6mm_P0.65mm_EP4.8x4.8mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_6x6mm_P0.65mm_EP4.8x4.8mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1209 Scripted replacement for qfn-20 (ATTiny MCUs)
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.25x2.25mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1208 Re export the qfn-2x footprints
  Package_DFN_QFN.pretty/MLF-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/MLF-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_3x3mm_P0.45mm_EP1.6x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_3x3mm_P0.45mm_EP1.6x1.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_3x4mm_P0.5mm_EP1.65x2.65mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_3x4mm_P0.5mm_EP1.65x2.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x5mm_P0.5mm_EP2.65x3.65mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x5mm_P0.5mm_EP2.65x3.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_5x5mm_P0.65mm_EP3.35x3.35mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_5x5mm_P0.65mm_EP3.35x3.35mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_3x3mm_P0.4mm_EP1.75x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_3x3mm_P0.4mm_EP1.75x1.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_3x4mm_P0.4mm_EP1.65x2.65mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_3x4mm_P0.4mm_EP1.65x2.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_5x5mm_P0.65mm_EP3.4x3.4mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_5x5mm_P0.65mm_EP3.4x3.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_3x6mm_P0.5mm_EP1.7x4.75mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_3x6mm_P0.5mm_EP1.7x4.75mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.45mm_EP2.4x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.45mm_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.4x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x5mm_P0.5mm_EP2.65x3.65mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x5mm_P0.5mm_EP2.65x3.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_5x5mm_P0.5mm_EP3.35x3.35mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_5x5mm_P0.5mm_EP3.35x3.35mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_5x6mm_P0.5mm_EP3.65x4.65mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_5x6mm_P0.5mm_EP3.65x4.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_6x6mm_P0.65mm_EP4.25x4.25mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-28_4x4mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/TQFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_PullBack.kicad_mod
  Package_DFN_QFN.pretty/TQFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_PullBack_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1203 Removing impossible qfn footprint
  Package_DFN_QFN.pretty/QFN-16-1EP_3x3mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1175 Add scripted TI S-PWSON-N8 (replaces #541)
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.2x2mm.kicad_mod
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.2x2mm_ThermalVias.kicad_mod
Labels: Addition

#1210 Scripted replacements for qfn-16-1ep 4x4mm EP2.5x2.5mm
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.5mm_EP2.45x2.45mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.5mm_EP2.45x2.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.15x2.15mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.15x2.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.7x2.7mm_PullBack.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.7x2.7mm_PullBack_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1061 add LFCSP-8-1EP 3x3mm variant (Analog cp-8-13)
  Package_CSP.pretty/LFCSP-8-1EP_3x3mm_P0.5mm_EP1.45x1.74mm.kicad_mod
Labels: Addition

#1229 Moved the courtyard to outside the pads
  RF_GPS.pretty/README.md
  RF_GPS.pretty/Sierra_XM11X0.kicad_mod
  RF_Module.pretty/Sierra_XA11X0.kicad_mod
  fp-lib-table
Labels: Addition

#1155 Ak300
  TerminalBlock_Altech.pretty/Altech_AK300_1x02_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x03_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x04_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x05_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x06_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x07_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x08_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x09_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x10_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x11_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x12_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x13_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x14_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x15_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x16_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x17_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x18_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x19_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x20_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x21_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x22_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x23_P5.00mm_45-Degree.kicad_mod
  TerminalBlock_Altech.pretty/Altech_AK300_1x24_P5.00mm_45-Degree.kicad_mod
  fp-lib-table
Labels: Addition, Pending changes

#1227 Rerun script for qfn-4x footprints
  Package_DFN_QFN.pretty/QFN-40-1EP_5x5mm_P0.4mm_EP3.6x3.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-40-1EP_5x5mm_P0.4mm_EP3.6x3.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-40-1EP_6x6mm_P0.5mm_EP4.6x4.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-40-1EP_6x6mm_P0.5mm_EP4.6x4.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-42-1EP_5x6mm_P0.4mm_EP3.7x4.7mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-42-1EP_5x6mm_P0.4mm_EP3.7x4.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_7x7mm_P0.5mm_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_7x7mm_P0.5mm_EP5.15x5.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_7x7mm_P0.5mm_EP5.2x5.2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_7x7mm_P0.5mm_EP5.2x5.2mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_8x8mm_P0.65mm_EP6.45x6.45mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_8x8mm_P0.65mm_EP6.45x6.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_5x5mm_P0.35mm_EP3.7x3.7mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_5x5mm_P0.35mm_EP3.7x3.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.3x4.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.3x4.3mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.3x5.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.3x5.3mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.45x5.45mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.45x5.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.6x5.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_7x7mm_P0.5mm_EP5.6x5.6mm_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1232 Reexport scripted qfn 56 and 68 footprints
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.5x5.2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.5x5.2mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP5.6x5.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP5.6x5.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-68-1EP_8x8mm_P0.4mm_EP5.2x5.2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-68-1EP_8x8mm_P0.4mm_EP5.2x5.2mm_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1236 qfn-56 8x8 (4.6x5.3 EP) removed
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.6x5.3mm.kicad_mod
Labels: Pending reviewer

#1230 Scripted replacements for qfn-48 6x6 (4.66x4.66 ep)
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.2x4.2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.2x4.2mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.66x4.66mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.66x4.66mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.6x4.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-48-1EP_6x6mm_P0.4mm_EP4.6x4.6mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1234 Scripted version of Texas X2QFN-12 (replaces #1221)
  Package_DFN_QFN.pretty/Texas_X2QFN-12_1.6x1.6mm_P0.4mm.kicad_mod
Labels: Addition, Pending reviewer

#1235 Scripted replacement for qfn-56 7x7 (5.7x5.7 EP)
  Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP5.6x5.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP5.6x5.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_7x7mm_P0.4mm_EP5.7x5.7mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1244 Move GPS's Modules to RF_GPS
  RF_GPS.pretty/Linx_RXM-GPS.kicad_mod
  RF_GPS.pretty/ublox_LEA.kicad_mod
  RF_GPS.pretty/ublox_MAX.kicad_mod
  RF_GPS.pretty/ublox_NEO.kicad_mod
  RF_GPS.pretty/ublox_SAM-M8Q.kicad_mod
  RF_GPS.pretty/ublox_SAM-M8Q_HandSolder.kicad_mod
Labels: Enhancement

#1228 Delete unneeded qfn-44 8x8 (6.6x6.6 ep)
  Package_DFN_QFN.pretty/QFN-44-1EP_8x8mm_P0.65mm_EP6.6x6.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-44-1EP_8x8mm_P0.65mm_EP6.6x6.6mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1041 Mounting holes for a PCB to DIN rail adapter
  MountingHole.pretty/DINRailAdapter_3xM3_PhoenixContact_1201578.kicad_mod
Labels: Addition

#989 Add Infineon PG-LLGA-5-1
  Sensor_Audio.pretty/Infineon_PG-LLGA-5-1.kicad_mod
Labels: Addition, Pending changes
