Repository KiCad/kicad-footprints, pull requests merged in 2018-10, with the labels that each got.

#988 Button_Switch_THT: Fix courtyard layer in EG1271
  Button_Switch_THT.pretty/SW_E-Switch_EG1271_DPDT.kicad_mod
Labels: Bug

#971 Magnetic buzzer kobitone 254 emb84 q ro
  Buzzer_Beeper.pretty/MagneticBuzzer_Kobitone_254-EMB84Q-RO.kicad_mod
Labels: Bug, Pending changes

#720 added part: Wells TSOP Socket 48pin
  Socket.pretty/Wells_648-0482211SA01.kicad_mod
Labels: Pending changes

#1043 New LED footprint 5381 series VCC
  LED_THT.pretty/LED_VCCLite_5381H1_6.35x6.35mm.kicad_mod
  LED_THT.pretty/LED_VCCLite_5381H3_6.35x6.35mm.kicad_mod
  LED_THT.pretty/LED_VCCLite_5381H5_6.35x6.35mm.kicad_mod
  LED_THT.pretty/LED_VCCLite_5381H7_6.35x6.35mm.kicad_mod
Labels: question
