Repository KiCad/kicad-footprints, pull requests merged in 2019-10, with the labels that each got.

#972 Add FC source files
  Sources/Inductor_SMD/L_Wuerth_WE-TPC-3816.FCStd
  Sources/Package_LGA/Infineon_PG-LLGA-5-1.FCStd
Labels: Addition, Pending footprint, Source

#1858 Add QFN-64-1EP_9x9mm_P0.5mm_EP3.8x3.8mm
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP3.8x3.8mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP3.8x3.8mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1365 Added USB_C_Plug_JAE_DX07P024AJ1.kicad_mod
  Connector_USB.pretty/USB_C_Plug_JAE_DX07P024AJ1.kicad_mod
Labels: Addition, ReadyForReview

#1306 Hirose DF3EA-xxP-2H
  Connector_Hirose.pretty/Hirose_DF3EA-02P-2H_1x02-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-03P-2H_1x03-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-04P-2H_1x04-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-05P-2H_1x05-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-06P-2H_1x06-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-07P-2H_1x07-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-08P-2H_1x08-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-09P-2H_1x09-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-10P-2H_1x10-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-11P-2H_1x11-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-12P-2H_1x12-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-13P-2H_1x13-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-14P-2H_1x14-1MP_P2.00mm_Horizontal.kicad_mod
  Connector_Hirose.pretty/Hirose_DF3EA-15P-2H_1x15-1MP_P2.00mm_Horizontal.kicad_mod
Labels: Addition, ReadyForReview

#1894 Molex spox tht side
  Connector_Molex.pretty/Molex_SPOX_5268-02A_1x02_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-03A_1x03_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-04A_1x04_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-05A_1x05_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-06A_1x06_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-07A_1x07_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-08A_1x08_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-09A_1x09_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-10A_1x10_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-11A_1x11_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-12A_1x12_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-13A_1x13_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-14A_1x14_P2.50mm_Horizontal.kicad_mod
  Connector_Molex.pretty/Molex_SPOX_5268-15A_1x15_P2.50mm_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#1892 new Tantalum packages from AVX F72 und F75 series
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-20_AVX-U.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-20_AVX-U_Pad2.72x3.50mm_HandSolder.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-28_AVX-C.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-28_AVX-C_Pad2.72x3.50mm_HandSolder.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-15_AVX-R.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-15_AVX-R_Pad2.68x6.30mm_HandSolder.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-20_AVX-M.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-20_AVX-M_Pad2.68x6.30mm_HandSolder.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-28_AVX-M.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-28_AVX-M_Pad2.68x6.30mm_HandSolder.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-38_AVX-R.kicad_mod
  Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-38_AVX-R_Pad2.68x6.30mm_HandSolder.kicad_mod
Labels: Addition, Pending reviewer

#1883 Add MQ-6 Gas Sensor
  Sensor.pretty/MQ-6.kicad_mod
Labels: Addition

#1901 Replace MSOP-8_3x3mm_P0.65mm with scripted version
  Package_SO.pretty/MSOP-8_3x3mm_P0.65mm.kicad_mod
Labels: Enhancement

#1707 Correct Tdson-8-1
  Package_TO_SOT_SMD.pretty/TDSON-8-1.kicad_mod
  Package_TO_SOT_SMD.pretty/TDSON-8-1_HandSoldering.kicad_mod
Labels: Bug

#1916 add L_Bourns-SRU1028
  Inductor_SMD.pretty/L_Bourns-SRU1028_10.0x10.0mm.kicad_mod
Labels: Addition

#1774 Inductor_SMD: Add Murata LQH2MCN_02 Chip coil (Chip Inductors) Series
  Inductor_SMD.pretty/L_Murata_LQH2MCNxxxx02_2.0x1.6mm.kicad_mod
Labels: Addition

#1447 Add Coilcraft XAL60xx
  Inductor_SMD.pretty/L_Coilcraft_XAL60xx_6.36x6.56mm.kicad_mod
Labels: Addition, ReadyForReview

#1888 add RJ45 connector Würth 74980111211
  Connector_RJ.pretty/RJ45_Wuerth_74980111211_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#1887 add RJ45 ethernet connector Pulse JXD6-0001NL
  Connector_RJ.pretty/RJ45_Pulse_JXD6-0001NL_Horizontal.kicad_mod
Labels: Addition

#1921 Adds EC15 (1.5x1.5mm) Footprint for SK6812 LED
  LED_SMD.pretty/LED_SK6812_EC15_1.5x1.5mm.kicad_mod
Labels: Addition, Pending changes

#1886 Adding JK0654219NL
  Connector_RJ.pretty/RJ45_Pulse_JK0654219NL_Horizontal.kicad_mod
Labels: Addition

#1898 Fixed coin cell holder negative contact size, removed from paste layer
  Battery.pretty/BatteryHolder_Keystone_3000_1x12mm.kicad_mod
  Battery.pretty/BatteryHolder_Keystone_3001_1x12mm.kicad_mod
  Battery.pretty/BatteryHolder_Keystone_3002_1x2032.kicad_mod
  Battery.pretty/BatteryHolder_Keystone_3008_1x2450.kicad_mod
  Battery.pretty/BatteryHolder_Keystone_3009_1x2450.kicad_mod
  Battery.pretty/BatteryHolder_Keystone_3034_1x20mm.kicad_mod
  Battery.pretty/BatteryHolder_LINX_BAT-HLD-012-SMT.kicad_mod
  Battery.pretty/BatteryHolder_MPD_BC2003_1x2032.kicad_mod
Labels: Bug, Enhancement

#1897 Add Littelfuse NANO2 45x series
  Fuse.pretty/Fuse_Littelfuse-NANO2-451_453.kicad_mod
Labels: Addition, Ready for review

#1515 Adding Samtec_FMC_ASP-134486-01_10x40_P1.27mm_Vertical connector
  Connector_Samtec.pretty/Samtec_FMC_ASP-134486-01_10x40_P1.27mm_Vertical.kicad_mod
Labels: Addition, Ready for review

#1800 Add Molex SL 171971
  Connector_Molex.pretty/Molex_SL_171971-0002_1x02_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0003_1x03_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0004_1x04_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0005_1x05_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0006_1x06_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0007_1x07_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0008_1x08_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0009_1x09_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0010_1x10_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0011_1x11_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0012_1x12_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0013_1x13_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0014_1x14_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0015_1x15_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0016_1x16_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0017_1x17_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0018_1x18_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0019_1x19_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0020_1x20_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0021_1x21_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0022_1x22_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0023_1x23_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0024_1x24_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_SL_171971-0025_1x25_P2.54mm_Vertical.kicad_mod
Labels: Addition, Ready for review

#1927 Add Taiyo-Yuden NR 10050 inductor footprint with handsoldering variant.
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-10050_9.8x10.0mm.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-10050_9.8x10.0mm_HandSoldering.kicad_mod
Labels: Addition

#1542 Added VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes, Re-push

#1540 Add Honeywell_CSLW
  Sensor_Current.pretty/Honeywell_CSLW.kicad_mod
Labels: Addition, Ready for review

#1879 Add Molex 47590-0001
  Connector_USB.pretty/USB_Micro-AB_Molex_47590-0001.kicad_mod
Labels: Addition, Pending changes

#1932 Add LFCSP-24
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.3x2.3mm.kicad_mod
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.3x2.3mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1931 Add LFCSP-WD, 10 Pin
  Package_CSP.pretty/LFCSP-WD-10-1EP_3x3mm_P0.5mm_EP1.64x2.38mm.kicad_mod
  Package_CSP.pretty/LFCSP-WD-10-1EP_3x3mm_P0.5mm_EP1.64x2.38mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1939 Adding TE 1734839 script generated FPC connectors
  Connector_FFC-FPC.pretty/TE_0-1734839-5_1x05-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_0-1734839-6_1x06-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_0-1734839-7_1x07-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_0-1734839-8_1x08-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_0-1734839-9_1x09-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-0_1x10-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-1_1x11-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-2_1x12-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-3_1x13-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-4_1x14-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-5_1x15-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-6_1x16-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-7_1x17-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-8_1x18-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_1-1734839-9_1x19-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-0_1x20-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-1_1x21-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-2_1x22-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-3_1x23-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-4_1x24-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-5_1x25-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-6_1x26-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-7_1x27-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-8_1x28-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_2-1734839-9_1x29-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-0_1x30-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-1_1x31-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-2_1x32-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-3_1x33-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-4_1x34-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-5_1x35-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-6_1x36-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-7_1x37-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-8_1x38-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_3-1734839-9_1x39-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-0_1x40-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-1_1x41-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-2_1x42-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-3_1x43-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-4_1x44-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-5_1x45-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-6_1x46-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-7_1x47-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-8_1x48-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_4-1734839-9_1x49-1MP_P0.5mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/TE_5-1734839-0_1x50-1MP_P0.5mm_Horizontal.kicad_mod
Labels: Addition, Pending changes

#1922 Add VQFN-46-1EP_5x6mm_P0.4mm_EP2.8x3.8mm (generated)
  Package_DFN_QFN.pretty/VQFN-46-1EP_5x6mm_P0.4mm_EP2.8x3.8mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-46-1EP_5x6mm_P0.4mm_EP2.8x3.8mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1709 Merge overlapping pads
  Package_DFN_QFN.pretty/ST_UFQFPN-20_3x3mm_P0.5mm.kicad_mod
  Package_TO_SOT_SMD.pretty/LFPAK33.kicad_mod
  Package_TO_SOT_SMD.pretty/LFPAK56.kicad_mod
  Package_TO_SOT_SMD.pretty/LFPAK56_ThermalVias-1.kicad_mod
  Package_TO_SOT_SMD.pretty/LFPAK56_ThermalVias-2.kicad_mod
  Package_TO_SOT_SMD.pretty/Vishay_PowerPAK_SC70-6L_Single.kicad_mod
Labels: Enhancement, Pending reviewer

#1941 Add Sunlord MWSA0518 Inductors
  Inductor_SMD.pretty/L_Sunlord_MWSA0518_5.4x5.2mm.kicad_mod
Labels: Addition, Pending changes

#1928 Connector_Coaxial: Fix and enhance SMA_Samtec_SMA-J-P-H-ST-EM1_EdgeMount
  Connector_Coaxial.pretty/SMA_Samtec_SMA-J-P-H-ST-EM1_EdgeMount.kicad_mod
  Connector_Coaxial.pretty/SMA_Samtec_SMA-J-P-X-ST-EM1_EdgeMount.kicad_mod
Labels: Bug, Enhancement, Pending reviewer

#1706 Update Pqfn 8x8
  Package_TO_SOT_SMD.pretty/PQFN_8x8.kicad_mod
Labels: Bug

#1945 Add Yuji 5730 LED footprint
  LED_SMD.pretty/LED_Yuji_5730.kicad_mod
Labels: Addition, Pending reviewer
