Repository KiCad/kicad-footprints, pull requests merged in 2019-11, with the labels that each got.

#1938 Adding PCB Edge PCI Express connectors
  Connector_PCBEdge.pretty/BUS_PCIexpress.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCIexpress_x1.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCIexpress_x16.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCIexpress_x4.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCIexpress_x8.kicad_mod
Labels: Addition, Pending changes

#1919 Adding IDT oscillator JS6 package footprint
  Oscillator.pretty/Oscillator_SMD_IDT_JS6-6_5.0x3.2mm_P1.27mm.kicad_mod
Labels: Addition, Pending changes

#1695 Add Amphenol RJHSE538X-02 connector
  Connector_RJ.pretty/RJ45_Amphenol_RJHSE538X-02.kicad_mod
Labels: Addition, Pending changes

#1671 Button_Switch_SMD: Add new Wuerth button
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_Vertical_Wuerth_434133025816.kicad_mod
Labels: Addition, Pending changes

#1565 Added AA battery holder - Keystone 2460
  Battery.pretty/BatteryHolder_Keystone_2460_1xAA.kicad_mod
Labels: Addition, Ready for review

#1940 Connector Abracon RJ45 ARJP11A-MA
  Connector_RJ.pretty/RJ45_Abracon_ARJP11A-MA_Horizontal.kicad_mod
Labels: Addition

#1936 Create RJ25_Wayconn_MJEA-660X1_Horizontal.kicad_mod
  Connector_RJ.pretty/RJ25_Wayconn_MJEA-660X1_Horizontal.kicad_mod
Labels: Addition

#1937 Add Diodes Inc PowerDI5 package
  Diode_SMD.pretty/D_PowerDI-5.kicad_mod
Labels: Addition, Ready for review

#1918 Adding IDT oscillator JU6 package footprint
  Oscillator.pretty/Oscillator_SMD_IDT_JU6-6_7.0x5.0mm_P2.54mm.kicad_mod
Labels: Addition

#1874 Add Molex KK 41691 Series
  Connector_Molex.pretty/Molex_KK-396_A-41791-0002_1x02_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0003_1x03_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0004_1x04_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0005_1x05_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0006_1x06_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0007_1x07_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0008_1x08_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0009_1x09_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0010_1x10_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0011_1x11_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0012_1x12_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0013_1x13_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0014_1x14_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0015_1x15_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0016_1x16_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0017_1x17_P3.96mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-396_A-41791-0018_1x18_P3.96mm_Vertical.kicad_mod
Labels: Addition, Ready for review

#1651 Add Kycon kdmix-sl1-ns-ws-b15
  Connector_HDMI.pretty/HDMI_A_Kycon_KDMIX-SL1-NS-WS-B15_VerticalRightAngle.kicad_mod
Labels: Addition, Pending changes

#1539 Added Johanson Balun 1.6 x 0.8 mm filter footprint
  RF_Converter.pretty/Balun_Johanson_1.6x0.8mm.kicad_mod
Labels: Addition, Ready for review

#1906 Reexport non EP qfp packages (ensrue script in sync with FPs)
  Package_QFP.pretty/LQFP-100_14x14mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-128_14x14mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-128_14x20mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-144_20x20mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-160_24x24mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-176_20x20mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-176_24x24mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-208_28x28mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-216_24x24mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-32_5x5mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-32_7x7mm_P0.8mm.kicad_mod
  Package_QFP.pretty/LQFP-36_7x7mm_P0.65mm.kicad_mod
  Package_QFP.pretty/LQFP-44_10x10mm_P0.8mm.kicad_mod
  Package_QFP.pretty/LQFP-48_7x7mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-52_10x10mm_P0.65mm.kicad_mod
  Package_QFP.pretty/LQFP-52_14x14mm_P1mm.kicad_mod
  Package_QFP.pretty/LQFP-64_10x10mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-64_14x14mm_P0.8mm.kicad_mod
  Package_QFP.pretty/LQFP-64_7x7mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-80_10x10mm_P0.4mm.kicad_mod
  Package_QFP.pretty/LQFP-80_12x12mm_P0.5mm.kicad_mod
  Package_QFP.pretty/LQFP-80_14x14mm_P0.65mm.kicad_mod
  Package_QFP.pretty/MQFP-44_10x10mm_P0.8mm.kicad_mod
  Package_QFP.pretty/PQFP-100_14x20mm_P0.65mm.kicad_mod
  Package_QFP.pretty/PQFP-144_28x28mm_P0.65mm.kicad_mod
  Package_QFP.pretty/PQFP-160_28x28mm_P0.65mm.kicad_mod
  Package_QFP.pretty/PQFP-208_28x28mm_P0.5mm.kicad_mod
  Package_QFP.pretty/PQFP-240_32.1x32.1mm_P0.5mm.kicad_mod
  Package_QFP.pretty/TQFP-100_14x14mm_P0.5mm.kicad_mod
  Package_QFP.pretty/TQFP-144_20x20mm_P0.5mm.kicad_mod
  Package_QFP.pretty/TQFP-176_24x24mm_P0.5mm.kicad_mod
  Package_QFP.pretty/TQFP-64_10x10mm_P0.5mm.kicad_mod
  Package_QFP.pretty/VQFP-100_14x14mm_P0.5mm.kicad_mod
  Package_QFP.pretty/VQFP-128_14x14mm_P0.4mm.kicad_mod
  Package_QFP.pretty/VQFP-176_20x20mm_P0.4mm.kicad_mod
  Package_QFP.pretty/VQFP-80_14x14mm_P0.65mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1908 Reexport SO footpritns to get script and FPs in sync
  Package_SO.pretty/MSOP-12_3x4mm_P0.65mm.kicad_mod
  Package_SO.pretty/MSOP-16_3x4.039mm_P0.5mm.kicad_mod
  Package_SO.pretty/MSOP-16_3x4mm_P0.5mm.kicad_mod
  Package_SO.pretty/MSOP-8_3x3mm_P0.65mm.kicad_mod
  Package_SO.pretty/SC-74-6_1.5x2.9mm_P0.95mm.kicad_mod
  Package_SO.pretty/SO-4_4.4x3.9mm_P2.54mm.kicad_mod
  Package_SO.pretty/SO-8_3.9x4.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-14W_7.5x9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-14_3.9x8.7mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16W_7.5x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16W_7.5x12.8mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16_3.9x9.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16_4.55x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-18W_7.5x11.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-20W_7.5x12.8mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-24W_7.5x15.4mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-28W_7.5x17.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-28W_7.5x18.7mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-4_4.55x2.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-4_4.55x3.7mm_P2.54mm.kicad_mod
  Package_SO.pretty/SOIC-8_3.9x4.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-8_5.23x5.23mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-8_5.275x5.275mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-8_7.5x5.85mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOJ-36_10.16x23.49mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-16_4.55x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-18_7x12.5mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-24_7.5x15.4mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-4_3.8x4.1mm_P2.54mm.kicad_mod
  Package_SO.pretty/SOP-4_4.4x2.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-8_3.76x4.96mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-8_3.9x4.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-8_5.28x5.23mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-8_6.62x9.15mm_P2.54mm.kicad_mod
  Package_SO.pretty/SSOP-20_5.3x7.2mm_P0.65mm.kicad_mod
  Package_SO.pretty/SSOP-32_11.305x20.495mm_P1.27mm.kicad_mod
  Package_SO.pretty/SSOP-8_3.9x5.05mm_P1.27mm.kicad_mod
  Package_SO.pretty/SSOP-8_5.25x5.24mm_P1.27mm.kicad_mod
  Package_SO.pretty/STC_SOP-16_3.9x9.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/TSOP-I-32_11.8x8mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSOP-II-44_10.16x18.41mm_P0.8mm.kicad_mod
  Package_SO.pretty/VSSOP-10_3x3mm_P0.5mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1905 QFP fix EP round radius (split #1821)
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP6.61x5.615mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP6.61x5.615mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP7.2x6.35mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP7.2x6.35mm_ThermalVias.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.7mm.kicad_mod
  Package_QFP.pretty/EQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.7mm_ThermalVias.kicad_mod
  Package_QFP.pretty/LQFP-48-1EP_7x7mm_P0.5mm_EP3.6x3.6mm.kicad_mod
  Package_QFP.pretty/LQFP-48-1EP_7x7mm_P0.5mm_EP3.6x3.6mm_ThermalVias.kicad_mod
  Package_QFP.pretty/LQFP-52-1EP_10x10mm_P0.65mm_EP4.8x4.8mm.kicad_mod
  Package_QFP.pretty/LQFP-52-1EP_10x10mm_P0.65mm_EP4.8x4.8mm_ThermalVias.kicad_mod
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP6.5x6.5mm.kicad_mod
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP6.5x6.5mm_ThermalVias.kicad_mod
  Package_QFP.pretty/TQFP-100-1EP_14x14mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/TQFP-100-1EP_14x14mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
  Package_QFP.pretty/TQFP-48-1EP_7x7mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/TQFP-48-1EP_7x7mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1909 Fix EP round radius for LFCSP footprints
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_4x4mm_P0.65mm_EP2.4x2.4mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_4x4mm_P0.65mm_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_CSP.pretty/LFCSP-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm.kicad_mod
  Package_CSP.pretty/LFCSP-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm.kicad_mod
  Package_CSP.pretty/LFCSP-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm.kicad_mod
  Package_CSP.pretty/LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-72-1EP_10x10mm_P0.5mm_EP5.3x5.3mm.kicad_mod
  Package_CSP.pretty/LFCSP-72-1EP_10x10mm_P0.5mm_EP5.3x5.3mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1911 Fix EP round radius for SON packages
  Package_SON.pretty/HVSON-8-1EP_4x4mm_P0.8mm_EP2.2x3.1mm.kicad_mod
  Package_SON.pretty/SON-8-1EP_3x2mm_P0.5mm_EP1.4x1.6mm.kicad_mod
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.2x2mm.kicad_mod
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.2x2mm_ThermalVias.kicad_mod
  Package_SON.pretty/VSON-10-1EP_3x3mm_P0.5mm_EP1.2x2mm.kicad_mod
  Package_SON.pretty/VSON-10-1EP_3x3mm_P0.5mm_EP1.2x2mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-12-1EP_4x4mm_P0.5mm_EP2.6x3mm.kicad_mod
  Package_SON.pretty/WSON-12-1EP_4x4mm_P0.5mm_EP2.6x3mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm.kicad_mod
  Package_SON.pretty/WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8-1EP_6x5mm_P1.27mm_EP3.4x4.3mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_6x5mm_P1.27mm_EP3.4x4mm.kicad_mod
Labels: Bug, Pending reviewer

#1914 Fix EP round radius of DFN footprints
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.7x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_1.2x1.2mm_P0.4mm_EP0.3x0.94mm_PullBack.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_2x1.8mm_P0.5mm_EP1.2x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_3x2mm_P0.5mm_EP1.65x1.35mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_3x3mm_P1mm_EP1.5x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.3mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.5mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x3mm_P0.65mm_EP1.7x2.05mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_4x4mm_P0.8mm_EP2.3x3.24mm.kicad_mod
  Package_DFN_QFN.pretty/MLF-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/MLF-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/MLF-6-1EP_1.6x1.6mm_P0.5mm_EP0.5x1.26mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PDSO-N10_EP1.2x2mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PDSO-N10_EP1.2x2mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_VSON-HR-8_1.5x2mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/WDFN-12-1EP_3x3mm_P0.45mm_EP1.7x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/WDFN-8-1EP_3x2mm_P0.5mm_EP1.3x1.4mm.kicad_mod
Labels: Bug, Pending reviewer

#1864 Added generic buzzer 14D, 7mm height, P10mm
  Buzzer_Beeper.pretty/Buzzer_D14mm_H7mm_P10mm.kicad_mod
Labels: Addition

#1604 Add 196-pin TFBGA, 0.75mm pitch, 0.32mm ball, 0.35 mm land for Microchip ATSAMA5D21
  Package_BGA.pretty/Microchip_TFBGA-196_11x11mm_Layout14x14_P0.75mm_SMD.kicad_mod
Labels: Addition

#1972 Fixed courtyard
  Button_Switch_THT.pretty/SW_Tactile_SKHH_Angled.kicad_mod
Labels: Bug
