Repository KiCad/kicad-footprints, pull requests merged in 2019-05, with the labels that each got.

#1472 Add Murata 1200RS inductor footprint
  Inductor_THT.pretty/L_Radial_D10.5mm_P4.00x5.00mm_Murata_1200RS.kicad_mod
Labels: Addition

#1570 NXP LGA-8
  Package_LGA.pretty/NXP_LGA-8_3x5mm_P1.25mm_H1.2mm.kicad_mod
Labels: Enhancement

#1344 Added script made foot print QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm
  Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1214 add SFP/SFP+ connector and cage
  Connector.pretty/Connector_SFP_and_Cage.kicad_mod
Labels: Addition, ReadyForReview

#1572 Added UDFN-9 package
  Package_DFN_QFN.pretty/UDFN-9_1.0x3.8mm_P0.5mm.kicad_mod
Labels: Addition

#1569 adds BGA footprints for Xilinx Virtex-7 FPGAs
  Package_BGA.pretty/Xilinx_FFG1157_FFG1158.kicad_mod
  Package_BGA.pretty/Xilinx_FFG1761.kicad_mod
  Package_BGA.pretty/Xilinx_FFG1926_FFG1927_FFG1928_FFG1930.kicad_mod
  Package_BGA.pretty/Xilinx_FFV1761.kicad_mod
  Package_BGA.pretty/Xilinx_FHG1761.kicad_mod
  Package_BGA.pretty/Xilinx_FLG1925_FLG1926_FLG1928_FLG1930.kicad_mod
  Package_BGA.pretty/Xilinx_RF1157_RF1158.kicad_mod
  Package_BGA.pretty/Xilinx_RF1761.kicad_mod
  Package_BGA.pretty/Xilinx_RF1930.kicad_mod
Labels: Addition

#1592 Button_Switch_SMD: improve slide switches descriptions
  Button_Switch_SMD.pretty/SW_SP3T_PCM13.kicad_mod
  Button_Switch_SMD.pretty/SW_SPDT_CK-JS102011SAQN.kicad_mod
  Button_Switch_SMD.pretty/SW_SPDT_PCM12.kicad_mod
Labels: Enhancement

#1413 add WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#939 Add Hirose df12c_ds and df12e_df
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-10DS-0.5V_2x05_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-14DS-0.5V_2x07_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-20DS-0.5V_2x10_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-30DS-0.5V_2x15_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-32DS-0.5V_2x16_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-36DS-0.5V_2x18_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-40DS-0.5V_2x20_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-50DS-0.5V_2x25_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12C3.0-60DS-0.5V_2x30_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-10DP-0.5V_2x05_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-14DP-0.5V_2x07_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-20DP-0.5V_2x10_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-30DP-0.5V_2x15_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-32DP-0.5V_2x16_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-36DP-0.5V_2x18_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-40DP-0.5V_2x20_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-50DP-0.5V_2x25_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-60DP-0.5V_2x30_P0.50mm_Vertical.kicad_mod
  Connector_Hirose.pretty/Hirose_DF12_DF12E3.0-80DP-0.5V_2x40_P0.50mm_Vertical.kicad_mod
Labels: Addition, ReadyForReview

#967 Mate n lok 350211 1
  Connector_TE-Connectivity.pretty/TE_MATE-N-LOK_350211-1_1x04_P5.08mm_Vertical.kicad_mod
Labels: Addition, ReadyForReview

#1608 Add WQFN-24
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Addition

#1595 SOIC 7.5x5.85mm (Texas DWV) footprint
  Package_SO.pretty/SOIC-8_7.5x5.85mm_P1.27mm.kicad_mod
Labels: Addition, Pending reviewer

#1581 Add Texas DRB
  Package_DFN_QFN.pretty/Texas_DRB0008A.kicad_mod
Labels: Addition, Pending reviewer

#1567 Add Bourns CD-DF4xxS footprint
  Diode_SMD.pretty/Diode_Bridge_Bourns_CD-DF4xxS.kicad_mod
Labels: Addition, Pending reviewer

#1591 Add Murata MGJ3 footprint
  Converter_DCDC.pretty/Converter_DCDC_Murata_MGJ3.kicad_mod
Labels: Addition, Pending reviewer

#1530 Add ADI CP-48-5 footprint
  Package_CSP.pretty/LFCSP-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm.kicad_mod
  Package_CSP.pretty/LFCSP-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1495 Create footprint for C&K switch PTS125SM43SMTR2-LFS
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_CK_PTS125Sx43PSMTR.kicad_mod
Labels: Addition
