Repository KiCad/kicad-footprints, pull requests merged in 2019-03, with the labels that each got.

#1442 Update Linear_DE14MA.kicad_mod
  Package_DFN_QFN.pretty/Linear_DE14MA.kicad_mod
Labels: Enhancement

#1457 Create Linear MSOP-12-16 for LT3748
  Package_SO.pretty/Linear_MSOP-12-16_3x4mm_P0.5mm.kicad_mod
Labels: Addition, Pending reviewer

#1459 Fix up footprint for TUSB7340
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N100_EP5.5x5.5mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N100_EP5.5x5.5mm_ThermalVias.kicad_mod
Labels: Addition

#1430 Stocko fix
  Connector_Stocko.pretty/Stocko_MKS_1651-6-0-202_1x2_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1652-6-0-202_1x2_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1653-6-0-303_1x3_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1654-6-0-404_1x4_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1655-6-0-505_1x5_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1656-6-0-606_1x6_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1657-6-0-707_1x7_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1658-6-0-808_1x8_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1659-6-0-909_1x9_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1660-6-0-1010_1x10_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1661-6-0-1111_1x11_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1662-6-0-1212_1x12_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1663-6-0-1313_1x13_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1664-6-0-1414_1x14_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1665-6-0-1515_1x15_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1666-6-0-1616_1x16_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1667-6-0-1717_1x17_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1668-6-0-1818_1x18_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1669-6-0-1919_1x19_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1670-6-0-2020_1x20_P2.50mm_Vertical.kicad_mod
Labels: Enhancement, Pending reviewer

#1350 Added Beagleboard pocket beagle foot print
  Module.pretty/BeagleBoard_PocketBeagle.kicad_mod
Labels: Addition

#1467 Fix Tensility 54-00023
  Connector_USB.pretty/USB_Mini-B_Tensility_54-00023_Vertical.kicad_mod
  Connector_USB.pretty/USB_Mini-B_Tensility_54-00023_Vertical_CircularHoles.kicad_mod
Labels: Bug

#1239 Add Panasonic Battery Vertical
  Battery.pretty/Battery_Panasonic_CR1025-VSK_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR1220-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR1632-V1AN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2025-V1AK_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2032-VS1N_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2354-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2450-VAN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2477-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR3032-VCN_Vertical_CircularHoles.kicad_mod
Labels: Addition, Pending changes

#1475 Add QFN-20 with EP2.7x2.7mm
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod
Labels: Addition

#1492 add scripted LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm
  Package_CSP.pretty/LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm.kicad_mod
  Package_CSP.pretty/LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1470 Vishay_PowerPAK_1212-8 custom pad zone connection to Solid
  Package_SO.pretty/Vishay_PowerPAK_1212-8_Dual.kicad_mod
  Package_SO.pretty/Vishay_PowerPAK_1212-8_Single.kicad_mod
Labels: Bug, Pending reviewer

#1439 Fix IRM-03 THT footprint
  Converter_ACDC.pretty/Converter_ACDC_MeanWell_IRM-03-xx_THT.kicad_mod
Labels: Bug, Pending reviewer

#1122 Added USB A vertical connector
  Connector_USB.pretty/USB_A_Molex_105057_Vertical.kicad_mod
Labels: Addition

#1345 Update of LED_PLCC_2835
  LED_SMD.pretty/LED_PLCC_2835.kicad_mod
  LED_SMD.pretty/LED_PLCC_2835_Handsoldering.kicad_mod
Labels: Enhancement, Pending changes

#1458 Add QFN-16 3x3mm P0.5mm EP1.75x1.75mm
  Package_DFN_QFN.pretty/QFN-16-1EP_3x3mm_P0.5mm_EP1.75x1.75mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_3x3mm_P0.5mm_EP1.75x1.75mm_ThermalVias.kicad_mod
Labels: Addition

#1371 Scripted version of non EP SOIC footprints
  Package_SO.pretty/SOIC-14W_7.5x9.0mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-14W_7.5x9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-14_3.9x8.7mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16W_7.5x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16W_7.5x12.8mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16_3.9x9.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-16_4.55x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-18W_7.5x11.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-20W_7.5x12.8mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-24W_7.5x15.4mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-28W_7.5x17.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-28W_7.5x18.7mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-8_3.9x4.9mm_P1.27mm.kicad_mod
Labels: Enhancement, ReadyForReview

#1488 Add SOP16 from STC (in essence a SOIC-16)
  Package_SO.pretty/STC_SOP-16_3.9x9.9mm_P1.27mm.kicad_mod
Labels: Addition, Pending changes

#1486 Add SOIC-8_5.23x5.23mm_P1.27mm
  Package_SO.pretty/SOIC-8_5.23x5.23mm_P1.27mm.kicad_mod
Labels: Addition, Pending reviewer

#1444 Add LFCSP-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm.
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.7x1.7mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1498 DFN_QFN: Add 10-pin DNF, 3x3mm with 1.7x2.5mm EP
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.7x2.5mm.kicad_mod
Labels: Addition, ReadyForReview

#1502 Added UDFN-8
  Package_DFN_QFN.pretty/OnSemi_UDFN-8_1.2x1.8mm_P0.4mm.kicad_mod
Labels: Addition, Pending reviewer

#1504 Correct dimensions on Keystone 2468
  Battery.pretty/BatteryHolder_Keystone_2468_2xAAA.kicad_mod
Labels: Bug, Pending reviewer

#1464 Added Omega2S Footprint
  Module.pretty/Onion_Omega2S.kicad_mod
Labels: Addition

#1424 TLP3123
  Package_SO.pretty/SO-4_4.4x3.9mm_P2.54mm.kicad_mod
Labels: Addition

#1513 Fix footprint for SOT-353_SC-70-5_Handsoldering
  Package_TO_SOT_SMD.pretty/SOT-353_SC-70-5_Handsoldering.kicad_mod
Labels: Bug, Pending reviewer

#1494 Adding BGA footprint for Analog/LT 28pin BGA
  Package_BGA.pretty/Analog_BGA-28_4.0x6.25mm_Layout4x7_P0.8mm_Ball0.45mm_Pad0.4.kicad_mod
Labels: Addition, Pending reviewer

#1512 Package_DFN_QFN: Add TQFN-16-1EP_5x5mm_P0.8mm_EP3.1x3.1mm
  Package_DFN_QFN.pretty/TQFN-16-1EP_5x5mm_P0.8mm_EP3.1x3.1mm.kicad_mod
Labels: Addition, Pending changes

#1084 Add RAYEX ELECTRONICS L90 Series 30A Relay
  Relay_THT.pretty/Relay_SPDT_RAYEX-L90.kicad_mod
  Relay_THT.pretty/Relay_SPDT_RAYEX-L90S.kicad_mod
  Relay_THT.pretty/Relay_SPST_RAYEX-L90A.kicad_mod
  Relay_THT.pretty/Relay_SPST_RAYEX-L90AS.kicad_mod
  Relay_THT.pretty/Relay_SPST_RAYEX-L90B.kicad_mod
  Relay_THT.pretty/Relay_SPST_RAYEX-L90BS.kicad_mod
Labels: Addition, Pending changes
