Repository KiCad/kicad-footprints, pull requests merged in 2019-09, with the labels that each got.

#1168 Connector_Card: Add microSD Molex 104031-0811
  Connector_Card.pretty/microSD_HC_Molex_104031-0811.kicad_mod
Labels: Addition, ReadyForReview

#1647 Footprint for TDFN-6 2.5x2.5mm Pitch 0.65mm Pad 2.0x1.3mm
  Package_DFN_QFN.pretty/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-6-1EP_2.5x2.5mm_P0.65mm_EP1.3x2mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1303 BatteryHolder: Add CH273-2450 (1 x CR2450)
  Battery.pretty/BatteryHolder_ComfortableElectronic_CH273-2450_1x2450.kicad_mod
Labels: Addition, ReadyForReview

#1571 Added LED footprint
  LED_SMD.pretty/LED_LiteOn_LTST-C19HE1WT.kicad_mod
Labels: Addition, Pending changes

#1794 Add footprints for XT60 male and female connectors.
  Connector_AMASS.pretty/AMASS_XT60-F_1x02_P7.20mm_Vertical.kicad_mod
  Connector_AMASS.pretty/AMASS_XT60-M_1x02_P7.20mm_Vertical.kicad_mod
Labels: Addition, Pending changes, Pending reviewer

#1474 Add the Laird BMI-S-230-F RF shield
  RF_Shielding.pretty/Laird_Technologies_BMI-S-230-F_50.8x38.1mm.kicad_mod
Labels: Addition, ReadyForReview

#1508 Adding JAE MXM connector MM70-314-310B1
  Connector_JAE.pretty/JAE_MM70-314-310B1.kicad_mod
Labels: Addition, ReadyForReview

#1723 Delevan 4222
  Inductor_SMD.pretty/L_CommonMode_Delevan_4222.kicad_mod
Labels: Addition, Pending reviewer

#1724 Add SMF diode footprint
  Diode_SMD.pretty/D_SMF.kicad_mod
Labels: Addition, Pending reviewer

#1725 Add SOD128 footprint
  Diode_SMD.pretty/D_SOD-128.kicad_mod
Labels: Addition, Pending reviewer

#1786 Add VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1768 add L_1008_2520Metric
  Inductor_SMD.pretty/L_1008_2520Metric.kicad_mod
Labels: Addition, Pending reviewer

#1783 add footprint for Schaffner FN406 EMI filter
  Filter.pretty/Filter_Schaffner_FN406.kicad_mod
Labels: Addition, Pending changes

#1417 add footprint for dual isolated BNC jacks
  Connector_Coaxial.pretty/BNC_Amphenol_031-6575_Horizontal.kicad_mod
  Connector_Coaxial.pretty/BNC_Win_364A2x95_Horizontal.kicad_mod
Labels: Addition, Pending changes

#1735 Murata LQH55DN inductor footprint
  Inductor_SMD.pretty/L_Murata_LQH55DN_5.7x5.0mm.kicad_mod
Labels: Addition, Pending reviewer

#1703 No number paste pads
  Package_TO_SOT_SMD.pretty/ATPAK-2.kicad_mod
  Package_TO_SOT_SMD.pretty/Rohm_HRP7.kicad_mod
Labels: Bug, Pending reviewer

#1682 Littelfuse 372
  Fuse.pretty/Fuse_Littelfuse_372_D8.50mm.kicad_mod
Labels: Addition, Pending reviewer

#1683 Lodestone vtm950 6
  Inductor_THT.pretty/L_Mount_Lodestone_VTM950-6.kicad_mod
Labels: Addition, Pending reviewer

#1650 Schurter 0031 8201 fix
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_Schurter_0031_8201_Horizontal_Open.kicad_mod
Labels: Bug, Enhancement, Pending reviewer

#1776 RF_Module: Add Modtronix inAir9 LoRa Module
  RF_Module.pretty/Modtronix_inAir9.kicad_mod
Labels: Addition, Pending reviewer

#1006 Add Jack_3.5mm_Switronic_ST-005-G_horizontal to Connector_Audio
  Connector_Audio.pretty/Jack_3.5mm_Switronic_ST-005-G_horizontal.kicad_mod
Labels: Addition, Pending changes

#1825 Fix DirectFET S1
  Package_DirectFET.pretty/DirectFET_S1.kicad_mod
Labels: Bug

#1823 Fix DirectFET SJ
  Package_DirectFET.pretty/DirectFET_SJ.kicad_mod
Labels: Bug

#1831 Fix DirectFET MZ
  Package_DirectFET.pretty/DirectFET_MZ.kicad_mod
Labels: Bug

#1829 Fix DirectFET MP
  Package_DirectFET.pretty/DirectFET_MP.kicad_mod
Labels: Bug

#1828 Fix DirectFET MX
  Package_DirectFET.pretty/DirectFET_MX.kicad_mod
Labels: Bug

#1827 Fix DirectFET MT
  Package_DirectFET.pretty/DirectFET_MT.kicad_mod
Labels: Bug

#1804 Fix DirectFET ME
  Package_DirectFET.pretty/DirectFET_ME.kicad_mod
Labels: Bug

#1830 Fix DirectFET MN
  Package_DirectFET.pretty/DirectFET_MN.kicad_mod
Labels: Bug

#1822 Fix DirectFET SQ
  Package_DirectFET.pretty/DirectFET_SQ.kicad_mod
Labels: Bug

#1832 Fix DirectFET L8
  Package_DirectFET.pretty/DirectFET_L8.kicad_mod
Labels: Bug

#1826 Fix DirectFET S2
  Package_DirectFET.pretty/DirectFET_S2.kicad_mod
Labels: Bug

#1824 Fix DirectFET SH
  Package_DirectFET.pretty/DirectFET_SH.kicad_mod
Labels: Bug

#1820 Fix DirectFET ST
  Package_DirectFET.pretty/DirectFET_ST.kicad_mod
Labels: Bug

#1837 Fix DirectFET S1 Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_S1.kicad_mod
Labels: Bug

#1838 Fix DirectFET S2 Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_S2.kicad_mod
Labels: Bug

#1807 Add DirectFET S3C
  Package_DirectFET.pretty/DirectFET_S3C.kicad_mod
Labels: Addition

#1759 add QFN-28-1EP_4x4mm_P0.4mm_EP2.6x2.6mm
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Addition

#1806 Add DirectFET SA
  Package_DirectFET.pretty/DirectFET_SA.kicad_mod
Labels: Addition

#1808 Add DirectFET SB
  Package_DirectFET.pretty/DirectFET_SB.kicad_mod
Labels: Addition

#1839 Fix DirectFET SH Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_SH.kicad_mod
Labels: Bug

#1811 Add DirectFET SC
  Package_DirectFET.pretty/DirectFET_SC.kicad_mod
Labels: Addition

#1842 Fix DirectFET ST Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_ST.kicad_mod
Labels: Bug

#1841 Fix DirectFET SQ Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_SQ.kicad_mod
Labels: Bug

#1840 Fix DirectFET SJ Fab and Courtyard
  Package_DirectFET.pretty/DirectFET_SJ.kicad_mod
Labels: Bug

#1784 Buzzer AT-0927-TT-6-R added
  Buzzer_Beeper.pretty/MagneticBuzzer_PUI_AT-0927-TT-6-R.kicad_mod
Labels: Addition

#1818 Add DirectFET L4
  Package_DirectFET.pretty/DirectFET_L4.kicad_mod
Labels: Addition

#1805 Add DirectFET L6
  Package_DirectFET.pretty/DirectFET_L6.kicad_mod
Labels: Addition

#1844 Fix DirectFET L8 silk and courtyard
  Package_DirectFET.pretty/DirectFET_L8.kicad_mod
Labels: Bug

#1845 Fix DirectFET L6 silk
  Package_DirectFET.pretty/DirectFET_L6.kicad_mod
Labels: Bug

#1819 Add DirectFET LA
  Package_DirectFET.pretty/DirectFET_LA.kicad_mod
Labels: Addition

#1809 Add DirectFET MC
  Package_DirectFET.pretty/DirectFET_MC.kicad_mod
Labels: Addition

#1810 Add DirectFET MD
  Package_DirectFET.pretty/DirectFET_MD.kicad_mod
Labels: Addition

#1803 Add DirectFET MF
  Package_DirectFET.pretty/DirectFET_MF.kicad_mod
Labels: Addition

#1846 Fix DirectFET ME fab, silk, pad height
  Package_DirectFET.pretty/DirectFET_ME.kicad_mod
Labels: Bug

#1847 Fix DirectFET MN fab and silk
  Package_DirectFET.pretty/DirectFET_MN.kicad_mod
Labels: Bug

#1848 Fix DirectFET MP fab and silk
  Package_DirectFET.pretty/DirectFET_MP.kicad_mod
Labels: Bug

#1849 Fix DirectFET MT fab and silk
  Package_DirectFET.pretty/DirectFET_MT.kicad_mod
Labels: Bug

#1856 Close courtyard of Omron B3F-10xx tactile switch.
  Button_Switch_THT.pretty/SW_TH_Tactile_Omron_B3F-10xx.kicad_mod
Labels: Bug

#1814 Add DirectFET M2
  Package_DirectFET.pretty/DirectFET_M2.kicad_mod
Labels: Addition, ReadyForReview

#1815 Add DirectFET M4
  Package_DirectFET.pretty/DirectFET_M4.kicad_mod
Labels: Addition, ReadyForReview

#1816 Add DirectFET MA
  Package_DirectFET.pretty/DirectFET_MA.kicad_mod
Labels: Addition, ReadyForReview

#1817 Add DirectFET MB
  Package_DirectFET.pretty/DirectFET_MB.kicad_mod
Labels: Addition, ReadyForReview

#1812 Add DirectFET MQ
  Package_DirectFET.pretty/DirectFET_MQ.kicad_mod
Labels: Addition, ReadyForReview

#1813 Add DirectFET MU
  Package_DirectFET.pretty/DirectFET_MU.kicad_mod
Labels: Addition, ReadyForReview

#1779 Add Dialight 591 series
  LED_SMD.pretty/LED_Dialight_591.kicad_mod
Labels: Addition, Pending changes

#1835 Fix MicroMELF footprints
  Diode_SMD.pretty/D_MicroMELF_Hadsoldering.kicad_mod
  Diode_SMD.pretty/D_MicroMELF_Handsoldering.kicad_mod
Labels: Bug

#1797 Added AST1109MLTRQ buzzer
  Buzzer_Beeper.pretty/Buzzer_Mallory_AST1109MLTRQ.kicad_mod
Labels: Addition

#1744 Add Atmel_ATSAMR21G18-MR210UA_NoRFPads
  RF_Module.pretty/Atmel_ATSAMR21G18-MR210UA_NoRFPads.kicad_mod
Labels: Addition, ReadyForReview

#1443 Add QFN 14 for SKY13575-639LF.
  Package_DFN_QFN.pretty/QFN-14-1EP_1.6x1.6mm_P0.4mm_EP0.74x0.74mm.kicad_mod
  RF.pretty/Skyworks_SKY13575_639LF.kicad_mod
Labels: Addition, ReadyForReview

#1867 Fix SW_TH_Tactile_Omron_B3F-10xx pin numbering
  Button_Switch_THT.pretty/SW_TH_Tactile_Omron_B3F-10xx.kicad_mod
Labels: Bug

#1736 Infineon TISON footprints
  Package_SON.pretty/Infineon_PG-TISON-8-2.kicad_mod
  Package_SON.pretty/Infineon_PG-TISON-8-3.kicad_mod
  Package_SON.pretty/Infineon_PG-TISON-8-4.kicad_mod
  Package_SON.pretty/Infineon_PG-TISON-8-5.kicad_mod
Labels: Addition, Question

#1866 7 seg footprint
  Display_7Segment.pretty/Sx39-1xxxxx.kicad_mod
Labels: Addition, Pending changes, Re-push

#1799 update Molex 47346 USB connector
  Connector_USB.pretty/USB_Micro-B_Molex_47346-0001.kicad_mod
Labels: Enhancement, Pending changes

#1854 Fix 7SegmentLED_LTS6760_LTS6780
  Display_7Segment.pretty/7SegmentLED_LTS6760_LTS6780.kicad_mod
Labels: Bug, Pending changes

#1733 Added Bourns SRN8040
  Inductor_SMD.pretty/L_Bourns-SRN8040_8x8.15mm.kicad_mod
Labels: Addition, ReadyForReview

#1599 Adding: SOP-8_3.9x4.9mm_P1.27mm, SOP-8_5.28x5.23mm_P1.27mm
  Package_SO.pretty/SOP-8_3.9x4.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-8_5.28x5.23mm_P1.27mm.kicad_mod
Labels: Addition, ReadyForReview

#1394 Add LPF-C012303S Lightpipe
  OptoDevice.pretty/Lightpipe_LPF-C012303S.kicad_mod
  fp-lib-table
Labels: Addition, ReadyForReview

#1511 Package_SO: Add TSOP-6_1.5x2.9mm_P0.95mm
  Package_SO.pretty/TSOP-6_1.5x2.9mm_P0.95mm.kicad_mod
Labels: Addition, ReadyForReview

#1873 Add SC-74 (replaces #1511)
  Package_SO.pretty/SC-74-6_1.5x2.9mm_P0.95mm.kicad_mod
Labels: Addition, Re-push

#1635 Converter_ACDC: Add CUI PBO-3 series
  Converter_ACDC.pretty/Converter_ACDC_CUI_PBO-3-Sxx_THT_Vertical.kicad_mod
Labels: Addition, Pending reviewer

#1633 Add scripted Infineon_PG-DSO-8-27 (replace #1448)
  Package_SO.pretty/Infineon_PG-DSO-8-27_3.9x4.9mm_EP2.65x3mm.kicad_mod
  Package_SO.pretty/Infineon_PG-DSO-8-27_3.9x4.9mm_EP2.65x3mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1693 L smd tdk
  Inductor_SMD.pretty/L_TDK_NLV25_2.5x2.0mm.kicad_mod
  Inductor_SMD.pretty/L_TDK_NLV32_3.2x2.5mm.kicad_mod
Labels: Addition, Pending changes

#1672 Connector_Wuerth: Add WR-WTB series
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800211622_1x02_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800311622_1x03_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800411622_1x04_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800511622_1x05_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800611622_1x06_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800711622_1x07_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800811622_1x08_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64800911622_1x09_P1.50mm_Vertical.kicad_mod
  Connector_Wuerth.pretty/Wuerth_WR-WTB_64801011622_1x10_P1.50mm_Vertical.kicad_mod
  fp-lib-table
Labels: Addition, Pending reviewer

#1652 Add TE 826576
  Connector_TE-Connectivity.pretty/TE_1-826576-3_1x13_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_1-826576-5_1x15_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_1-826576-6_1x16_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_1-826576-7_1x17_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_1-826576-8_1x18_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_2-826576-0_1x20_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_3-826576-6_1x36_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-2_1x02_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-3_1x03_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-5_1x05_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-6_1x06_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-7_1x07_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-8_1x08_P3.96mm_Vertical.kicad_mod
  Connector_TE-Connectivity.pretty/TE_826576-9_1x09_P3.96mm_Vertical.kicad_mod
Labels: Addition, Question

#1727 Clean up and correct TO-277A
  Package_TO_SOT_SMD.pretty/TO-277A.kicad_mod
Labels: Enhancement

#1871 Added DFN-8-1EP_4x4mm_P0.8mm_EP2.3x3.24mm
  Package_DFN_QFN.pretty/DFN-8-1EP_4x4mm_P0.8mm_EP2.3x3.24mm.kicad_mod
Labels: Addition, Pending changes

#1870 Added QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1788 Add HTSSOP-28-1EP_4.4x9.7mm_P0.65mm_EP2.85x5.4mm
  Package_SO.pretty/HTSSOP-28-1EP_4.4x9.7mm_P0.65mm_EP2.85x5.4mm.kicad_mod
  Package_SO.pretty/HTSSOP-28-1EP_4.4x9.7mm_P0.65mm_EP2.85x5.4mm_ThermalVias.kicad_mod
Labels: Addition

#1865 Adding Texas_VSON-HR-8_1.5x2mm_P0.5mm
  Package_DFN_QFN.pretty/Texas_VSON-HR-8_1.5x2mm_P0.5mm.kicad_mod
Labels: Addition, Pending changes, Scripting required

#1752 Add Wago 236 series 2-pin terminal blocks
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-401_1x01_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-402_1x02_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-403_1x03_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-404_1x04_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-406_1x06_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-408_1x08_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-412_1x12_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-416_1x16_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-424_1x24_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-436_1x36_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-448_1x48_P5.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-501_1x01_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-502_1x02_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-503_1x03_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-504_1x04_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-506_1x06_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-508_1x08_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-512_1x12_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-516_1x16_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-524_1x24_P7.50mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-601_1x01_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-602_1x02_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-603_1x03_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-604_1x04_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-606_1x06_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-608_1x08_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-612_1x12_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-616_1x16_P10.00mm_45Degree.kicad_mod
  TerminalBlock_WAGO.pretty/TerminalBlock_WAGO_236-624_1x24_P10.00mm_45Degree.kicad_mod
Labels: Addition

#1708 UDFN-4_1x1mm_P0.65mm update
  Package_DFN_QFN.pretty/UDFN-4-1EP_1x1mm_P0.65mm_EP0.48x0.48mm.kicad_mod
  Package_DFN_QFN.pretty/UDFN-4_1x1mm_P0.65mm.kicad_mod
Labels: Enhancement

#1665 add Filter Shaffner FN405
  Filter.pretty/Filter_Schaffner_FN405.kicad_mod
Labels: Addition, ReadyForReview

#1661 Varistor: Add a new models
  Varistor.pretty/RV_Disc_D16.5mm_W6.7mm_P7.5mm.kicad_mod
  Varistor.pretty/RV_Disc_D9mm_W6.1mm_P5mm.kicad_mod
Labels: Addition, ReadyForReview

#1639 Add switch KMR2 with ground pin
  Button_Switch_SMD.pretty/SW_Push_1P1T-SH_NO_CK_KMR2xxG.kicad_mod
Labels: Addition, ReadyForReview

#1721 Inductor_SMD: Add Sumida CDMC6D28 SMD Power Inductor Series
  Inductor_SMD.pretty/L_Sumida_CDMC6D28_7.25x6.5mm.kicad_mod
Labels: Addition, Pending reviewer

#1731 Inductor_SMD: Add Bourns SRP7028A Shielded Power Inductors Series
  Inductor_SMD.pretty/L_Bourns_SRP7028A_7.3x6.6mm.kicad_mod
Labels: Addition, Pending reviewer

#1705 Fix/update Hvsof5 footprint
  Package_TO_SOT_SMD.pretty/HVSOF5.kicad_mod
Labels: Bug, Pending reviewer

#1700 SMD inductors to custom pads
  Inductor_SMD.pretty/L_Coilcraft_LPS4018.kicad_mod
  Inductor_SMD.pretty/L_Wuerth_WE-TPC-3816.kicad_mod
Labels: Enhancement, Pending reviewer

#1726 Connector_USB: Add USB Mini-B Wuerth 65100516121
  Connector_USB.pretty/USB_Mini-B_Wuerth_65100516121_Horizontal.kicad_mod
Labels: Addition

#1741 QFN-64 9x9mm EP4.35x4.35mm
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP4.35x4.35mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP4.35x4.35mm_ThermalVias.kicad_mod
Labels: Addition
