Repository KiCad/kicad-footprints, pull requests merged in 2019-07, with the labels that each got.

#1648 Lt347x dfn10
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.65x2.38mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1666 Infineon qfn64
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP5.45x5.45mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP5.45x5.45mm_ThermalVias.kicad_mod
Labels: Addition

#1675 Added datasheet link
  Crystal.pretty/Crystal_AT310_D3.0mm_L10.0mm_Horizontal.kicad_mod
  Crystal.pretty/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style1.kicad_mod
  Crystal.pretty/Crystal_AT310_D3.0mm_L10.0mm_Horizontal_1EP_style2.kicad_mod
  Crystal.pretty/Crystal_AT310_D3.0mm_L10.0mm_Vertical.kicad_mod
Labels: Enhancement

#1658 New Footprint Converter_DCDC_Murata_MGJ2DxxxxxxSC_THT for MGJ2DxxxxxxSC
  Converter_DCDC.pretty/Converter_DCDC_Murata_MGJ2DxxxxxxSC_THT.kicad_mod
Labels: Addition

#1688 Close courtyard
  Battery.pretty/BatteryHolder_Keystone_3000_1x12mm.kicad_mod
Labels: Enhancement

#1742 LED-APA102-2020: Move F.Fab marker
  LED_SMD.pretty/LED-APA102-2020.kicad_mod
Labels: Enhancement, Pending reviewer

#1631 Added HRO TYPE-C-31-M-12
  Connector_USB.pretty/USB_C_Receptacle_HRO_TYPE-C-31-M-12.kicad_mod
Labels: Addition, Pending changes

#1751 HRO_TYPE-C-31-M-12: remove USB symbol on Fab layer
  Connector_USB.pretty/USB_C_Receptacle_HRO_TYPE-C-31-M-12.kicad_mod
Labels: Enhancement

#1728 Add Finder 36.11 10A SPDT relay footprint
  Relay_THT.pretty/Relay_SPDT_Finder_36.11.kicad_mod
Labels: Addition, Pending KLC issue, Pending reviewer
