Repository KiCad/kicad-footprints, pull requests merged in 2019-01, with the labels that each got.

#873 add VSSOP-10 0.5mm pin pitch
  Package_SO.pretty/VSSOP-10_3x3mm_P0.5mm.kicad_mod
Labels: Addition, Pending changes

#1069 Fixes for consistency with other footprints
  Connector_Audio.pretty/Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical_CircularHoles.kicad_mod
Labels: Enhancement, Pending reviewer

#1170 Xbga 121 10x10mm
  Package_BGA.pretty/XBGA-121_10x10mm_Layout11x11_P0.8mm.kicad_mod
Labels: Addition

#1035 ECS-2520MV oscillator footprint
  Oscillator.pretty/Oscillator_SMD_ECS_2520MV-xxx-xx-4Pin_2.5x2.0mm.kicad_mod
Labels: Addition, Pending changes

#976 Fujitsu wlp 8 3.09x2.28mm pitch0.4mm
  Package_BGA.pretty/Fujitsu_WLP-15_2.28x3.092mm_Layout3x5_P0.4mm.kicad_mod
Labels: Addition, Pending changes

#1127 Mini-Circuits land-pattern PL-052
  Package_SO.pretty/Mini-Circuits_CD542_LandPatternPL-052.kicad_mod
Labels: Addition, Pending reviewer

#1130 Add Mini-Circuits land pattern PL-035
  Package_SO.pretty/Mini-Circuits_CD636_LandPatternPL-035.kicad_mod
Labels: Addition, Pending reviewer

#824 Add vertical RJ-45 connector On-Shore PJ012-8P8CX
  Connector_RJ.pretty/RJ45_OST_PJ012-8P8CX_Vertical.kicad_mod
Labels: Addition

#1136 add Mini-Circuits land-pattern PL-176
  Package_SO.pretty/Mini-Circuits_GP731_LandPatternPL-176.kicad_mod
Labels: Addition, Pending reviewer

#1134 add Mini-Circuits land-pattern PL-230
  Package_SO.pretty/Mini-Circuits_HF1139_LandPatternPL-230.kicad_mod
Labels: Addition, Pending reviewer

#1044 Converter dcdc mu rata ncs1 sxxxx sc tht
  Converter_DCDC.pretty/Converter_DCDC_Murata_NCS1SxxxxSC_THT.kicad_mod
Labels: Addition, Pending changes

#1135 add Mini-Circuits land-pattern PL-236
  Package_SO.pretty/Mini-Circuits_QQQ130_LandPattern_PL-236_ClockwisePinNumbering.kicad_mod
Labels: Addition, Pending changes

#1128 Add Mini-Circuits PL-258 land-pattern
  Package_SO.pretty/Mini-Circuits_TT1224_LandPatternPL-258__ClockwisePinNumbering.kicad_mod
Labels: Addition, Pending changes

#1252 MountingEquipment: moving DIN Rail adapter
  MountingEquipment.pretty/DINRailAdapter_3xM3_PhoenixContact_1201578.kicad_mod
  fp-lib-table
Labels: Enhancement

#1256 Fix TO-92 Flat (was mirrored plus KLC errors)
  Package_TO_SOT_THT.pretty/TO-92Flat.kicad_mod
Labels: Bug, Pending reviewer

#1126 Mini-Circuits PL-005 land-pattern
  Package_SO.pretty/Mini-Circuits_BK377_LandPatternPL-005.kicad_mod
Labels: Addition, Pending changes

#909 add Oscillator_SMD_Abracon_ASCO-4Pin_1.6x1.2mm
  Oscillator.pretty/Oscillator_SMD_Abracon_ASCO-4Pin_1.6x1.2mm.kicad_mod
Labels: Addition, Pending changes

#888 Vishay WSR2/3 footprint
  Resistor_SMD.pretty/R_Shunt_Vishay_WSR2_WSR3.kicad_mod
  Resistor_SMD.pretty/R_Shunt_Vishay_WSR2_WSR3_KelvinConnection.kicad_mod
Labels: Addition, ReadyForReview

#1174 Transformers: Add footprint for Excelitas ZS1052 AC ignition coil
  Transformer_THT.pretty/Autotransformer_ZS1052-AC.kicad_mod
Labels: Addition, Pending reviewer

#1277 Move Sierra XA11X0 to RF_GPS
  RF_GPS.pretty/Sierra_XA11X0.kicad_mod
Labels: Enhancement

#1269 Added LFCSP-WQ-24-7EP_4x4mm_P0.5mm_EP2.6416x2.6416mm
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias.kicad_mod
Labels: Addition

#1110 Add VCXO Abracon ABLNO
  Oscillator.pretty/Oscillator_SMD_Abracon_ABLNO.kicad_mod
Labels: Addition, ReadyForReview

#1266 Scripted WSON-6 (replace #1241)
  Package_SON.pretty/WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm.kicad_mod
  Package_SON.pretty/WSON-6-1EP_2x2mm_P0.65mm_EP1x1.6mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1261 Scripted fp for Silicon Labs Si512/513 oscillator
  Oscillator.pretty/Oscillator_SMD_Silicon_Labs_LGA-6_2.5x3.2mm_P1.25mm.kicad_mod
Labels: Addition

#726 Added WeMos D1 Mini module
  Module.pretty/WEMOS_D1_mini_light.kicad_mod
Labels: Addition, Pending changes

#1212 Texas drc0010j
  Package_SON.pretty/Texas_DRC0010J.kicad_mod
  Package_SON.pretty/Texas_DRC0010J_ThermalVias.kicad_mod
Labels: Addition

#925 Add Lattice 381-ball 0.8mm pitch caBGA footprint.
  Package_BGA.pretty/Lattice_caBGA-381_17.0x17.0mm_Layout20x20_P0.8mm_Ball0.4mm_Pad0.4mm_NSMD.kicad_mod
  Package_BGA.pretty/Lattice_caBGA-381_17.0x17.0mm_Layout20x20_P0.8mm_Ball0.4mm_Pad0.6mm_SMD.kicad_mod
Labels: Addition, ReadyForReview

#884 Finish #703: TE Miniature PCB Relay PCH_A
  Relay_THT.pretty/Relay_SPST_TE_PCH-1xxx2M.kicad_mod
Labels: Addition, Pending changes

#1133 Add Mini-Circuits land-pattern PL-079
  Package_SO.pretty/Mini-Circuits_TTT167_LandPatternPL-079.kicad_mod
Labels: Addition, Pending changes

#1106 Murata BNX025 EMI-filter
  Filter.pretty/Filter_Murata_BNX025.kicad_mod
  Filter.pretty/Filter_Murata_BNX025_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1132 Add Mini-Circuits land pattern PL-247
  Package_SO.pretty/Mini-Circuits_HZ1198_LandPatternPL-247.kicad_mod
Labels: Addition, ReadyForReview

#1023 Add Lodestone VTM inductor mount footprints
  Inductor_THT.pretty/L_Mount_Lodestone_VTM120.kicad_mod
  Inductor_THT.pretty/L_Mount_Lodestone_VTM160.kicad_mod
  Inductor_THT.pretty/L_Mount_Lodestone_VTM254.kicad_mod
  Inductor_THT.pretty/L_Mount_Lodestone_VTM280.kicad_mod
Labels: Addition, ReadyForReview

#1287 KiCad Logos: Master Update to Build
  Symbol.pretty/KiCad-Logo2_12mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_12mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_12mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_12mm_SilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_20mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_20mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_20mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_20mm_SilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_30mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_30mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_30mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_30mm_SilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_40mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_40mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_40mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_40mm_SilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_5mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_5mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_5mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_6mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_6mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_6mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_8mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo2_8mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo2_8mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo2_8mm_SilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_12mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_12mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_12mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_20mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_20mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_20mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_30mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_30mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_30mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_40mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_40mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_40mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_5mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_5mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_5mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_6mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_6mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_6mm_FSolderMask.kicad_mod
  Symbol.pretty/KiCad-Logo_8mm_FCopper.kicad_mod
  Symbol.pretty/KiCad-Logo_8mm_FSilkScreen.kicad_mod
  Symbol.pretty/KiCad-Logo_8mm_FSolderMask.kicad_mod
  Symbol.pretty/Symbol_KiCAD-Logo_CopperAndSilkScreenTop.kicad_mod
Labels: Enhancement, Pending changes

#986 Add PT61017PEL Ethernet LAN Transformer
  Transformer_SMD.pretty/Transformer_Ethernet_Bourns_PT61017PEL.kicad_mod
Labels: Addition

#1151 add Mini-Circuits land pattern PL-012
  Package_SO.pretty/Mini-Circuits_CK605_LandPatternPL-012.kicad_mod
Labels: Addition

#1251 Add vertical USB Type-C DX07S024WJ1
  Connector_USB.pretty/USB_C_Receptacle_JAE_DX07S024WJ1R350.kicad_mod
Labels: Addition

#1213 RF_Module: Fix and improves HOPERF_RFM9XW_SMD footprint
  RF_Module.pretty/HOPERF_RFM9XW_SMD.kicad_mod
Labels: Enhancement

#1180 Rename Cherry MX1A to Cherry MX
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.00u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.00u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.50u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.50u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.75u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.75u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Vertical_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Vertical_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.75u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.75u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_6.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_6.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_ISOEnter_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_ISOEnter_Plate.kicad_mod
Labels: Enhancement, Pending reviewer

#495 More 3M Textool ZIF sockets, generated with script.
  Socket.pretty/DIP_Socket-14_W4.3_W5.08_W7.62_W10.16_W10.9_3M_214-3339-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-18_W4.3_W5.08_W7.62_W10.16_W10.9_3M_218-3341-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-20_W4.3_W5.08_W7.62_W10.16_W10.9_3M_220-3342-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-22_W6.9_W7.62_W10.16_W12.7_W13.5_3M_222-3343-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-24_W11.9_W12.7_W15.24_W17.78_W18.5_3M_224-1275-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-24_W4.3_W5.08_W7.62_W10.16_W10.9_3M_224-5248-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-28_W11.9_W12.7_W15.24_W17.78_W18.5_3M_228-1277-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-28_W6.9_W7.62_W10.16_W12.7_W13.5_3M_228-4817-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-32_W11.9_W12.7_W15.24_W17.78_W18.5_3M_232-1285-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-40_W11.9_W12.7_W15.24_W17.78_W18.5_3M_240-1280-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-40_W22.1_W22.86_W25.4_W27.94_W28.7_3M_240-3639-00-0602J.kicad_mod
  Socket.pretty/DIP_Socket-42_W11.9_W12.7_W15.24_W17.78_W18.5_3M_242-1281-00-0602J.kicad_mod
Labels: Addition, ReadyForReview

#1058 Converter_DCDC XP_POWER IA, IH, ITX and ITQ series
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IA48xxD_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IA48xxS_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IAxxxxD_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IAxxxxS_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IHxxxxDH_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IHxxxxD_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IHxxxxSH_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-IHxxxxS_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-ITQxxxxS-H_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-ITXxxxxSA_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-ITxxxxxS_THT.kicad_mod
Labels: Addition, ReadyForReview

#1299 Add L_Wuerth_WE-PD-Typ-7345.
  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-7345.kicad_mod
Labels: Addition, ReadyForReview

#1296 RF Module: Add CMWX1ZZABZ
  RF_Module.pretty/CMWX1ZZABZ.kicad_mod
Labels: Addition, ReadyForReview

#1215 Sip package link fixes
  Package_SIP.pretty/PowerIntegrations_eSIP-7F.kicad_mod
  Package_SIP.pretty/SIP4_Sharp-SSR_P7.62mm_Angled_NoHole.kicad_mod
  Package_SIP.pretty/SLA704XM.kicad_mod
Labels: Enhancement, ReadyForReview

#1218 Seiko ms621 f
  Battery.pretty/BatteryHolder_Seiko_MS621F.kicad_mod
Labels: Addition, ReadyForReview

#1300 RJ45: Add a new Amphenol RJHSE5380-08 footprint
  Connector_RJ.pretty/RJ45_Amphenol_RJHSE5380-08.kicad_mod
Labels: Addition, Pending changes

#1270 Crystal: Add Abracon ABS25 4Pin 8.0x3.8mm
  Crystal.pretty/Crystal_SMD_Abracon_ABS25-4Pin_8.0x3.8mm.kicad_mod
Labels: Addition, Pending changes

#1284 Added Kyocera 6 pin tcxo.
  Oscillator.pretty/Oscillator_SMD_Kyocera_2520-6Pin_2.5x2.0mm.kicad_mod
Labels: Addition

#1325 Mini-Circuits PL-258: fix typo "__" -> "_"
  Package_SO.pretty/Mini-Circuits_TT1224_LandPatternPL-258_ClockwisePinNumbering.kicad_mod
Labels: Bug

#1297 Add SHT1x - temperature/humidity sensor
  Sensor_Temperature.pretty/SHT1x.kicad_mod
  fp-lib-table
Labels: Addition, ReadyForReview

#1289 Add skyworks dfn 6.
  RF.pretty/Skyworks_SKY65404-31.kicad_mod
  fp-lib-table
Labels: Addition

#1281 Added DC4759J5020AHF.
  RF_Converter.pretty/Anaren_0805_2012Metric-6.kicad_mod
Labels: Addition, Pending changes

#1248 Add footprint for Maxim Integrated TSOC-6
  Package_SO_J-Lead.pretty/TSOC-6_3.76x3.94mm_P1.27mm.kicad_mod
  fp-lib-table
Labels: Addition, Pending changes

#1293 Add WSON-8-1EP_6x5mm_P1.27mm_E3.4x4.3mm.
  Package_SON.pretty/WSON-8-1EP_6x5mm_P1.27mm_EP3.4x4.3mm.kicad_mod
Labels: Addition, ReadyForReview

#1305 Varistor: Add a 4.9 width version
  Varistor.pretty/RV_Disc_D7mm_W4.9mm_P5mm.kicad_mod
Labels: Addition, ReadyForReview

#1314 Mini-Circuits BK377 plain footprint
  Package_SO.pretty/Mini-Circuits_BK377.kicad_mod
Labels: Addition, ReadyForReview

#1324 Mini-Circuits TT1224
  Package_SO.pretty/Mini-Circuits_TT1224_ClockwisePinNumbering.kicad_mod
Labels: Addition, Pending reviewer

#1323 Add Mini-Circuits QQQ130 plain footprint
  Package_SO.pretty/Mini-Circuits_QQQ130_ClockwisePinNumbering.kicad_mod
Labels: Addition, Pending reviewer

#1318 plain version of Mini-Circuits MMM168
  Package_SO.pretty/Mini-Circuits_MMM168.kicad_mod
Labels: Addition, Pending reviewer

#1317 Plain version of Mini-Circuits HF1139
  Package_SO.pretty/Mini-Circuits_HF1139.kicad_mod
Labels: Addition, Pending reviewer

#1315 Mini-Circuits GP731/GP1212 plain footprint
  Package_SO.pretty/Mini-Circuits_GP1212.kicad_mod
  Package_SO.pretty/Mini-Circuits_GP731.kicad_mod
Labels: Addition, Pending reviewer

#1319 Update 16-pin Textool socket to match all the others
  Socket.pretty/DIP_Socket-16_W4.3_W5.08_W7.62_W10.16_W10.9_3M_216-3340-00-0602J.kicad_mod
Labels: Enhancement, Pending reviewer

#1220 add Bourns SRF0905 line filter
  Filter.pretty/Filter_Bourns_SRF0905_6.0x9.2mm.kicad_mod
Labels: Addition, Pending reviewer

#1330 Mini-Circuits HZ1198
  Package_SO.pretty/Mini-Circuits_HZ1198.kicad_mod
Labels: Addition

#1328 Mini-Circuits CK605
  Package_SO.pretty/Mini-Circuits_CK605.kicad_mod
Labels: Addition

#1037 Vishay_PowerPAK_SO-8 removing
  Package_SO.pretty/Vishay_PowerPAK_SO-8.kicad_mod
Labels: Enhancement, Pending reviewer

#1329 Mini-Circuits TTT167
  Package_SO.pretty/Mini-Circuits_TTT167.kicad_mod
  Package_SO.pretty/Mini-Circuits_TTT167_LandPatternPL-079.kicad_mod
Labels: Addition, Pending changes

#1321 TO-SOT SMD: Add footprint for On Semiconductor ECH8 package
  Package_TO_SOT_SMD.pretty/OnSemi_ECH8.kicad_mod
Labels: Addition, Pending changes

#1334 add QFN-12-1EP variant from Mini-Circuits DQ1225
  Package_DFN_QFN.pretty/QFN-12-1EP_3x3mm_P0.51mm_EP1.45x1.45mm.kicad_mod
Labels: Addition, Pending changes

#1283 New QFN 24 for 2.8x2.8mm EP.
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1285 Add QFN-64-1EP_9x9mm_P0.5mm_EP7.15x7.15mm.
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP7.15x7.15mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP7.15x7.15mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1286 Add DFN-8 with 0.8x1.2mm EP.
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.3mm.kicad_mod
Labels: Addition, Pending changes

#754 Button_Switch_SMD: Rename KMR2 footprint to include manufacturer
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_CK_KMR2.kicad_mod
Labels: Enhancement, ReadyForReview

#1339 Moving mini circuits footprints out of Package_SO lib
  RF_Mini-Circuits.pretty/Mini-Circuits_BK377.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_BK377_LandPatternPL-005.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD541_H2.08mm.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD542_H2.84mm.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD542_LandPatternPL-052.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD542_LandPatternPL-094.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD636_H4.11mm.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD636_LandPatternPL-035.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CD637_H5.23mm.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CK605.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_CK605_LandPatternPL-012.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_GP1212.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_GP1212_LandPatternPL-176.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_GP731.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_GP731_LandPatternPL-176.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_HF1139.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_HF1139_LandPatternPL-230.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_HZ1198.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_HZ1198_LandPatternPL-247.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_MMM168.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_MMM168_LandPatternPL-225.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_QQQ130_ClockwisePinNumbering.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_QQQ130_LandPattern_PL-236_ClockwisePinNumbering.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_TT1224_ClockwisePinNumbering.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_TT1224_LandPatternPL-258_ClockwisePinNumbering.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_TTT167.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_TTT167_LandPatternPL-079.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_YY161.kicad_mod
  RF_Mini-Circuits.pretty/Mini-Circuits_YY161_LandPatternPL-049.kicad_mod
  fp-lib-table
Labels: Enhancement

#1222 Added Footrpints for Hanrun HR911105A 10/100 Ethernet Magjack & Traco…
  Connector_RJ.pretty/RJ45_Hanrun_HR911105A.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_TRACO_TMR-2xxxxWI_THT.kicad_mod
Labels: Addition, Pending changes

#1219 Footprint for Quectel BC66
  RF_GSM.pretty/Quectel_BC66.kicad_mod
Labels: Addition, ReadyForReview
