Repository KiCad/kicad-footprints, pull requests merged in 2019-06, with the labels that each got.

#1262 SJ1-3535NG stereo 3.5mm audio jack with switch
  Connector_Audio.pretty/Jack_3.5mm_CUI_SJ1-3535NG_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_CUI_SJ1-3535NG_Horizontal_CircularHoles.kicad_mod
Labels: Addition, Pending reviewer

#1338 Add LTST-S326 series right-angle LEDs
  LED_SMD.pretty/LED_LiteOn_LTST-S326.kicad_mod
Labels: Addition, Pending reviewer

#1426 add AD cp-32-2 footprint for LFCSP-32 package
  Package_CSP.pretty/LFCSP-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm.kicad_mod
  Package_CSP.pretty/LFCSP-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1598 Added HUSON-3 diode footprint
  Package_SON.pretty/HUSON-3-1EP_2x2mm_P1.3mm_EP1.1x1.6mm.kicad_mod
Labels: Addition, Pending changes

#1611 added scripted Texas_S-PX2QFN-14
  Package_DFN_QFN.pretty/Texas_S-PX2QFN-14.kicad_mod
Labels: Addition, Pending changes

#1622 Added BatteryHolder_Keystone_3002
  Battery.pretty/BatteryHolder_Keystone_3002_1x2032.kicad_mod
Labels: Addition

#1620 Add QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1352 Added DIP-8-16 foot print
  Package_DIP.pretty/DIP-8-16_W7.62mm.kicad_mod
  Package_DIP.pretty/DIP-8-16_W7.62mm_Socket.kicad_mod
  Package_DIP.pretty/DIP-8-16_W7.62mm_Socket_LongPads.kicad_mod
Labels: Addition, Pending reviewer

#1562 Added TI SWRA416 PCB antenna footprint
  RF_Antenna.pretty/Texas_SWRA416_868MHz_915MHz.kicad_mod
Labels: Addition

#1438 add footprint for E-Switch TL1250
  Button_Switch_THT.pretty/SW_Push_1P1T_NO_LED_E-Switch_TL1250.kicad_mod
Labels: Addition, Pending changes

#1454 add E-Switch 800U in M6 variant
  Button_Switch_THT.pretty/SW_Push_1P2T_Vertical_E-Switch_800UDP8P1A1M6.kicad_mod
  Button_Switch_THT.pretty/SW_Push_2P2T_Vertical_E-Switch_800UDP8P1A1M6.kicad_mod
Labels: Addition, Pending changes

#1429 Mentor 4 way lightpipes 1276.1004 and 1276.2004
  OptoDevice.pretty/Lightpipe_Mentor_1276.1004.kicad_mod
  OptoDevice.pretty/Lightpipe_Mentor_1276.2004.kicad_mod
Labels: Addition, Pending changes

#1503 Abracon ASPI-0630LR inductor
  Inductor_SMD.pretty/L_Abracon_ASPI-0630LR.kicad_mod
Labels: Addition, Pending changes

#1054 Add molex EDGELOCK
  Connector_PCBEdge.pretty/molex_EDGELOCK_2-CKT.kicad_mod
  Connector_PCBEdge.pretty/molex_EDGELOCK_4-CKT.kicad_mod
  Connector_PCBEdge.pretty/molex_EDGELOCK_6-CKT.kicad_mod
  Connector_PCBEdge.pretty/molex_EDGELOCK_8-CKT.kicad_mod
Labels: Addition, Pending changes

#1603 Converter_ACDC: Add TMG 15 series
  Converter_ACDC.pretty/Converter_ACDC_TRACO_TMG-15_THT.kicad_mod
Labels: Addition, Pending reviewer

#1456 add SMA jack Amphenol 132203-12
  Connector_Coaxial.pretty/SMA_Amphenol_132203-12_Horizontal.kicad_mod
Labels: Addition, ReadyForReview

#1062 add Mini-Circuits XX112 SO package
  Package_SO.pretty/SOP-8-1EP_4.57x4.57mm_P1.27mm_EP4.57x4.45mm.kicad_mod
  Package_SO.pretty/SOP-8-1EP_4.57x4.57mm_P1.27mm_EP4.57x4.45mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1607 Added NXP_LGA-8 for MPL3115A2
  Package_LGA.pretty/NXP_LGA-8_3x5mm_P1.25mm_H1.1mm.kicad_mod
Labels: Addition, ReadyForReview

#1601 Package_SO: Add SOIC 8 5.257x5.275
  Package_SO.pretty/SOIC-8_5.275x5.275mm_P1.27mm.kicad_mod
Labels: Addition, ReadyForReview

#789 Added Palconn UTC16-G connector
  Connector_USB.pretty/USB_C_Receptacle_Palconn_UTC16-G.kicad_mod
Labels: Addition, ReadyForReview

#1628 added L_Bourns_SRN8040TA
  Inductor_SMD.pretty/L_Bourns_SRN8040TA.kicad_mod
Labels: Addition, Pending reviewer

#1625 Add QFN-40 footprint for IS31FL3736/7
  Package_DFN_QFN.pretty/QFN-40-1EP_5x5mm_P0.4mm_EP3.8x3.8mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-40-1EP_5x5mm_P0.4mm_EP3.8x3.8mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1605 Add VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1630 Fix courtyard clearances for scripted no lead footprints with pull back pins
  Oscillator.pretty/Oscillator_SMD_Silicon_Labs_LGA-6_2.5x3.2mm_P1.25mm.kicad_mod
  Package_LGA.pretty/Bosch_LGA-8_3x3mm_P0.8mm_ClockwisePinNumbering.kicad_mod
  Package_LGA.pretty/LGA-14_2x2mm_P0.35mm_LayoutBorder3x4y.kicad_mod
  Package_LGA.pretty/LGA-14_3x2.5mm_P0.5mm_LayoutBorder3x4y.kicad_mod
  Package_LGA.pretty/LGA-14_3x5mm_P0.8mm_LayoutBorder1x6y.kicad_mod
  Package_LGA.pretty/LGA-16_3x3mm_P0.5mm_LayoutBorder3x5y.kicad_mod
  Package_LGA.pretty/LGA-16_4x4mm_P0.65mm_LayoutBorder4x4y.kicad_mod
  Package_LGA.pretty/ST_HLGA-10_2.5x2.5mm_P0.6mm_LayoutBorder3x2y.kicad_mod
  Package_LGA.pretty/Texas_SIL0008D_MicroSiP-8-1EP_2.8x3mm_P0.65mm_EP1.1x1.9mm.kicad_mod
  Package_LGA.pretty/Texas_SIL0008D_MicroSiP-8-1EP_2.8x3mm_P0.65mm_EP1.1x1.9mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x2.5mm_P0.5mm_EP1.2x1.5mm_PullBack_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1461 Add LQFP-64-1EP_10x10mm_P0.5mm_EP5x5mm
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP5x5mm.kicad_mod
  Package_QFP.pretty/LQFP-64-1EP_10x10mm_P0.5mm_EP5x5mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1349 Replacement of PR499
  Package_SO.pretty/MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm.kicad_mod
  Package_SO.pretty/MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-16_3x4.039mm_P0.5mm.kicad_mod
Labels: Addition, ReadyForReview

#1021 Tdk inductor
  Inductor_SMD.pretty/L_TDK_SLF10145.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF10165.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF12555.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF12565.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF12575.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF6025.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF6028.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF6045.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF7032.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF7045.kicad_mod
  Inductor_SMD.pretty/L_TDK_SLF7055.kicad_mod
Labels: Addition, ReadyForReview

#1632 added QFN-72-1EP_10x10mm_P0.5mm_EP6x6mm
  Package_DFN_QFN.pretty/QFN-72-1EP_10x10mm_P0.5mm_EP6x6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-72-1EP_10x10mm_P0.5mm_EP6x6mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1593 Fix pad orientation of SW_Push_1P1T_NO_CK_KMR2
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_CK_KMR2.kicad_mod
Labels: Bug

#1460 Package_DFN_QFN: Add Texas R-PVQFN-N24
  Package_DFN_QFN.pretty/Texas_RGY_R-PVQFN-N24_EP2.05x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGY_R-PVQFN-N24_EP2.05x3.1mm_ThermalVias.kicad_mod
Labels: Addition

#1653 add LFCSP-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm
  Package_CSP.pretty/LFCSP-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_CSP.pretty/LFCSP-20-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1640 Add SOP-24_7.5x15.4mm_P1.27mm
  Package_SO.pretty/SOP-24_7.5x15.4mm_P1.27mm.kicad_mod
Labels: Addition, Pending reviewer

#1636 added FFC molex series 502231
  Connector_FFC-FPC.pretty/Molex_502231-1500_1x15-1SH_P0.5mm_Vertical.kicad_mod
  Connector_FFC-FPC.pretty/Molex_502231-2400_1x24-1SH_P0.5mm_Vertical.kicad_mod
  Connector_FFC-FPC.pretty/Molex_502231-3300_1x33-1SH_P0.5mm_Vertical.kicad_mod
Labels: Addition, Pending reviewer

#1641 added Texas_S-PVQFN-N16_EP2.1x2.1mm footprint
  Package_DFN_QFN.pretty/Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm_ThermalVias.kicad_mod
Labels: Addition, Scripting required

#1667 Increase hole size to 1.3mm
  Button_Switch_THT.pretty/SW_PUSH-12mm.kicad_mod
Labels: Bug, Enhancement, Pending reviewer
