Repository KiCad/kicad-footprints, pull requests merged in 2019-04, with the labels that each got.

#1435 Oscillator: Add Abracon ASDMB
  Oscillator.pretty/Oscillator_SMD_Abracon_ASDMB-4Pin_2.5x2.0mm.kicad_mod
Labels: Addition

#1520 Correct NPTH to 1.27mm
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0215_1x02_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0315_1x03_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0415_1x04_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0515_1x05_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0615_1x06_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0715_1x07_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0815_1x08_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-0915_1x09_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-1015_1x10_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-1115_1x11_P3.00mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Micro-Fit_3.0_43650-1215_1x12_P3.00mm_Vertical.kicad_mod
Labels: Bug

#1514 Package_DFN_QFN: Add Texas_S-PWQFN-N32_EP2.8x2.8mm
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N32_EP2.8x2.8mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N32_EP2.8x2.8mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1480 Button_Switch_SMD: Add a 6x6 1P1T button
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_6x6mm_H9.5mm.kicad_mod
Labels: Addition, ReadyForReview

#1465 Create WE 750343373
  Transformer_THT.pretty/Transformer_Wuerth_750343373.kicad_mod
Labels: Addition

#1484 Amass xt30
  Connector_AMASS.pretty/AMASS_MR30PW-FB_1x03_P3.50mm_Horizontal.kicad_mod
  Connector_AMASS.pretty/AMASS_MR30PW-M_1x03_P3.50mm_Horizontal.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30PW-F_1x02_P2.50mm_Horizontal.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30PW-M_1x02_P2.50mm_Horizontal.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30U-F_1x02_P5.0mm_Vertical.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30U-M_1x02_P5.0mm_Vertical.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30UPB-F_1x02_P5.0mm_Vertical.kicad_mod
  Connector_AMASS.pretty/AMASS_XT30UPB-M_1x02_P5.0mm_Vertical.kicad_mod
  fp-lib-table
Labels: Addition, Pending reviewer

#1529 Fix line thicknesses on a few parts
  Battery.pretty/BatteryHolder_Bulgin_BX0036_1xC.kicad_mod
  Battery.pretty/BatteryHolder_MPD_BH-18650-PC2.kicad_mod
  Connector_Pin.pretty/Pin_D1.4mm_L8.5mm_W2.8mm_FlatFork.kicad_mod
  Filter.pretty/Filter_1109-5_1.1x0.9mm.kicad_mod
  Filter.pretty/Filter_1411-5_1.4x1.1mm.kicad_mod
  Package_SIP.pretty/SIP4_Sharp-SSR_P7.62mm_Angled_NoHole.kicad_mod
  Package_SIP.pretty/SLA704XM.kicad_mod
Labels: Enhancement

#1505 Add footprint for RTC RV-1805-C3
  Package_SON.pretty/RTC_SMD_MicroCrystal_C3_2.5x3.7mm.kicad_mod
Labels: Addition, Pending reviewer

#1466 Add Texas RNN0018A for TPS568215
  Package_DFN_QFN.pretty/Texas_RNN0018A.kicad_mod
Labels: Addition

#1390 Add shield pads
  Connector_RJ.pretty/RJ45_Wuerth_7499010121A_Horizontal.kicad_mod
Labels: Enhancement

#1395 Add Texas RGE0024C footprint
  Package_DFN_QFN.pretty/Texas_RGE0024C_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024C_EP2.1x2.1mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1154 Add Footprint support of USR USR-C322.
  RF_WiFi.pretty/USR-C322.kicad_mod
  fp-lib-table
Labels: Addition, Pending changes

#1468 Added USB_A SS-52100-001 connector
  Connector_USB.pretty/USB_A_Stewart_SS-52100-001_Horizontal.kicad_mod
Labels: Addition, ReadyForReview

#1347 RF_Module: Fix issues of HOPERF_RFM9XW_THT (#1346)
  RF_Module.pretty/HOPERF_RFM9XW_THT.kicad_mod
Labels: Enhancement, Pending changes

#1543 Add 3.5x3.5mm QFN-20 with 2mm pad.
  Package_DFN_QFN.pretty/QFN-20-1EP_3.5x3.5mm_P0.5mm_EP2x2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-20-1EP_3.5x3.5mm_P0.5mm_EP2x2mm_ThermalVias.kicad_mod
Labels: Addition

#1557 [RFC] adds BGA packages for Xilinx 7 Artix FPGAs
  Package_BGA.pretty/Xilinx_CPG236.kicad_mod
  Package_BGA.pretty/Xilinx_CPG238.kicad_mod
  Package_BGA.pretty/Xilinx_CSG324.kicad_mod
  Package_BGA.pretty/Xilinx_CSG325.kicad_mod
  Package_BGA.pretty/Xilinx_FBG484.kicad_mod
  Package_BGA.pretty/Xilinx_FBG676.kicad_mod
  Package_BGA.pretty/Xilinx_FFG1156.kicad_mod
  Package_BGA.pretty/Xilinx_FGG484.kicad_mod
  Package_BGA.pretty/Xilinx_FGG676.kicad_mod
  Package_BGA.pretty/Xilinx_FTG256.kicad_mod
  Package_BGA.pretty/Xilinx_RB484.kicad_mod
  Package_BGA.pretty/Xilinx_RB676.kicad_mod
  Package_BGA.pretty/Xilinx_RS484.kicad_mod
  Package_BGA.pretty/Xilinx_SBG484.kicad_mod
Labels: Addition

#1532 Add TI TO-PMOD-11 / NDY0011A
  Package_TO_SOT_SMD.pretty/Texas_NDY0011A.kicad_mod
Labels: Addition

#1563 fix pin numbering for Omron G6S-2, -2F, and -2G DPDT relays
  Relay_SMD.pretty/Relay_DPDT_Omron_G6S-2F.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Omron_G6S-2G.kicad_mod
  Relay_THT.pretty/Relay_DPDT_Omron_G6S-2.kicad_mod
Labels: Bug, Pending reviewer
