Repository KiCad/kicad-footprints, pull requests merged in 2019-02, with the labels that each got.

#1279 NKK GW12xxH SPDT right-angle rocker switch
  Button_Switch_THT.pretty/SW_Lever_1P2T_NKK_GW12LxH.kicad_mod
Labels: Addition, Pending changes

#1348 Added HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3x3mm and HTSSOP-24-1EP_4.4x7.8…
  Package_SO.pretty/HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3x3mm.kicad_mod
  Package_SO.pretty/HTSSOP-24-1EP_4.4x7.8mm_P0.65mm_EP3.2x5mm.kicad_mod
Labels: Addition

#1361 Remove duplicate TI WSON-6
  Package_DFN_QFN.pretty/Texas_S-PWSON-N6.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWSON-N6_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1362 Remove dublicate TI VQFN-RGR-20
  Package_DFN_QFN.pretty/Texas_VQFN-RGR-20.kicad_mod
Labels: Enhancement, Pending reviewer

#1363 Replace TI VQFN-RGW-20 with scripted version
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP3.15x3.15mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP3.15x3.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_VQFN-RGW-20.kicad_mod
Labels: Enhancement, Pending reviewer

#1368 Scripted SOIC-8-1EP footprint for LM5017MR
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.95x4.9mm_Mask2.71x3.4mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.95x4.9mm_Mask2.71x3.4mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1373 Scripted MSOP-8 EP for PM8834M
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.95x2.15mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.95x2.15mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1374 Scripted MSOP-8 EP for LM25085MY and LM3407MY
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.73x1.85mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.73x1.85mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1366 Scripted SOIC-8-1EP footprint for HIP2100
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.514x3.2mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.514x3.2mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1369 Remove old SOIC-8 ep footprint
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.35x2.35mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1375 Add MSOP-8 EP (mask defined) for MIC5355-S4YMME
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.54x2.8mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.54x2.8mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.5x3mm_Mask1.73x2.36mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.5x3mm_Mask1.73x2.36mm_ThermalVias.kicad_mod
Labels: Addition, Enhancement, Pending reviewer

#1340 Coilcraft LPS5030 shielded power inductor
  Inductor_SMD.pretty/L_Coilcraft_LPS5030.kicad_mod
  Sources/Inductor_SMD/L_Coilcraft_LPS5030.FCStd
Labels: Addition, ReadyForReview

#1376 Fix Cherry and Matias keyswitch Fab line thickness
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.00u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.00u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.50u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.50u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.75u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_1.75u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Vertical_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.00u_Vertical_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.75u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_2.75u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_6.25u_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_6.25u_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_ISOEnter_PCB.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Cherry_MX_ISOEnter_Plate.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_1.00u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_1.25u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_1.50u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_1.75u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_2.00u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_2.25u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_2.75u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_6.25u.kicad_mod
  Button_Switch_Keyboard.pretty/SW_Matias_ISOEnter.kicad_mod
Labels: Enhancement

#1246 Added 7 segment display SA15-11
  Display_7Segment.pretty/SA15-11xxx.kicad_mod
Labels: Addition, Pending changes

#1117 Add D52M
  RF_Module.pretty/Garmin_M8-35_9.8x14.0mm_Layout6x6_P1.5mm.kicad_mod
Labels: Addition

#1072 Rename SIP-3 Packages in Sensor_Current
  Sensor_Current.pretty/Diodes_SIP-3_4.1x1.5mm_P1.27mm.kicad_mod
  Sensor_Current.pretty/Diodes_SIP-3_4.1x1.5mm_P2.65mm.kicad_mod
  Sensor_Current.pretty/Diodes_SIP-3_AmmoPack.kicad_mod
Labels: Enhancement, ReadyForReview

#1085 Connector: Add B6A-PCB-45 from IHI connectors
  Connector.pretty/IHI_B6A-PCB-45_Vertical.kicad_mod
Labels: Addition, ReadyForReview

#1217 add Fischer FK244_13_D2_PAK SMD heatsink
  Heatsink.pretty/Heatsink_Fischer_FK24413D2PAK_26x13mm.kicad_mod
Labels: Addition, ReadyForReview

#1355 Added SIM28ML footprint
  RF_GPS.pretty/SIM28ML.kicad_mod
Labels: Addition

#1359 Added battery holder BatteryHolder_TruPower_BH-331P_3xAA
  Battery.pretty/BatteryHolder_TruPower_BH-331P_3xAA.kicad_mod
Labels: Addition

#1357 Add SPST relay TE PCN-1xxD3MHZ
  Relay_THT.pretty/Relay_SPST_TE_PCN-1xxD3MHZ.kicad_mod
Labels: Addition

#761 Button_Switch_THT: Add CK OS102011MS2QN1 footprint
  Button_Switch_THT.pretty/SW_Slide_1P2T_CK_OS102011MS2Q.kicad_mod
Labels: Addition, Pending changes, Question

#1383 Add Molex 200528 series (scripted via kicad-footprint-generator)
  Connector_FFC-FPC.pretty/Molex_200528-0040_1x04-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0050_1x05-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0060_1x06-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0070_1x07-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0080_1x08-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0090_1x09-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0100_1x10-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0110_1x11-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0120_1x12-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0130_1x13-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0140_1x14-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0150_1x15-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0160_1x16-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0170_1x17-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0180_1x18-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0190_1x19-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0200_1x20-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0210_1x21-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0220_1x22-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0230_1x23-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0240_1x24-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0250_1x25-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0260_1x26-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0270_1x27-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0280_1x28-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0290_1x29-1MP_P1.00mm_Horizontal.kicad_mod
  Connector_FFC-FPC.pretty/Molex_200528-0300_1x30-1MP_P1.00mm_Horizontal.kicad_mod
Labels: Addition, ReadyForReview

#1326 add new vertical fuseholders
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_EATON_H15-V-1_Vertical_Closed.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_EATON_HBV_Vertical_Closed.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_EATON_HBW_Vertical_Closed.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_Schurter_FPG4_Vertical_Closed.kicad_mod
Labels: Addition, Pending changes

#1382 Added footprint for RECOM RPM-series of DC/DC converters (1A, 2A, 3A and 6A).
  Converter_DCDC.pretty/Converter_DCDC_RECOM_RPMx.x-x.0.kicad_mod
Labels: Addition, Question

#1405 Add QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm
  Package_DFN_QFN.pretty/QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_8x8mm_P0.4mm_EP6.5x6.5mm_ThermalVias.kicad_mod
Labels: Addition

#1401 Scripted TI S-PWQFN-N16 EP2.1 for motor drivers
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N16_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N16_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_4x4mm_P0.65mm_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_4x4mm_P0.65mm_EP2.1x2.1mm_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1402 Scripted pwqfn-n24 for BQ25601
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N24_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N24_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod
Labels: Enhancement, Pending reviewer

#1358 Reexport texas qfn footpritns with updated scripts
  Package_DFN_QFN.pretty/Texas_R-PWQFN-N28_EP2.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_R-PWQFN-N28_EP2.1x3.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024H_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024H_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N16_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N16_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.4x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N24_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N24_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N32_EP3.45x3.45mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N32_EP3.45x3.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N48_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N48_EP5.15x5.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N64_EP4.25x4.25mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N64_EP4.25x4.25mm_ThermalVias.kicad_mod
Labels: Enhancement

#1066 Add Raspberry Pi Zero footprint using Through-hole pin socket
  Module.pretty/Raspberry_Pi_Zero_Socketed_THT_FaceDown_MountingHoles.kicad_mod
Labels: Addition, ReadyForReview

#1173 Connector_Audio: Add Jack_3.5mm_CUI_SJ-3523-SMT_Horizontal/Jack_3.5mm_CUI_SJ-3524-SMT_Horizontal
  Connector_Audio.pretty/Jack_3.5mm_CUI_SJ-3523-SMT_Horizontal.kicad_mod
  Connector_Audio.pretty/Jack_3.5mm_CUI_SJ-3524-SMT_Horizontal.kicad_mod
Labels: Addition

#1196 OptoDevice: Add APDS-9306-065
  OptoDevice.pretty/Broadcom_DFN-6_2x2mm_P0.65mm.kicad_mod
  OptoDevice.pretty/Broadcom_LGA-8_2x2mm_P0.53mm.kicad_mod
Labels: Addition, ReadyForReview

#755 Button_Switch_SMD: Add KSC7 button from CK switches
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_CK_KSC6xxJ.kicad_mod
  Button_Switch_SMD.pretty/SW_Push_1P1T_NO_CK_KSC7xxJ.kicad_mod
Labels: Addition, ReadyForReview

#1311 add Onion Omega2+ footprint
  Module.pretty/Onion_Omega2+.kicad_mod
Labels: Addition, Pending changes

#1403 Add Stocko_MKS_16XX Connectors
  Connector_Stocko.pretty/Stocko_MKS_1651-6-0-202_1x2_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1652-6-0-202_1x2_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1653-6-0-303_1x3_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1654-6-0-404_1x4_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1655-6-0-505_1x5_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1656-6-0-606_1x6_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1657-6-0-707_1x7_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1658-6-0-808_1x8_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1659-6-0-909_1x9_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1660-6-0-1010_1x10_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1661-6-0-1111_1x11_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1662-6-0-1212_1x12_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1663-6-0-1313_1x13_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1664-6-0-1414_1x14_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1665-6-0-1515_1x15_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1666-6-0-1616_1x16_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1667-6-0-1717_1x17_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1668-6-0-1818_1x18_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1669-6-0-1919_1x19_P2.50mm_Vertical.kicad_mod
  Connector_Stocko.pretty/Stocko_MKS_1670-6-0-2020_1x20_P2.50mm_Vertical.kicad_mod
  fp-lib-table
Labels: Addition, ReadyForReview

#1393 Add TRAPC5M 5-Pin Mini-XLR Connector
  Connector_Audio.pretty/MiniXLR-5_Switchcraft_TRAPC_Horizontal.kicad_mod
Labels: Addition, ReadyForReview

#1295 Added data sheet links to a number of fuse foot prints and renamed one fuse foot print
  Fuse.pretty/Fuseholder_Blade_Mini_Keystone_3568.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_Bulgin_FX0456_Vertical_Closed.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_Schurter_0031-8002_Horizontal_Open.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-5x20mm_Schurter_0031_8201_Horizontal_Open.kicad_mod
  Fuse.pretty/Fuseholder_Cylinder-6.3x32mm_Schurter_0031-8002_Horizontal_Open.kicad_mod
  Fuse.pretty/Fuseholder_TR5_Littelfuse_No560_No460.kicad_mod
Labels: Addition, Enhancement, Pending changes, Question

#1389 Add LED-APA102-2020
  LED_SMD.pretty/LED-APA102-2020.kicad_mod
Labels: Addition, ReadyForReview

#1377 Scripted MSOP-10 EP for A4952_LY
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.73x1.98mm.kicad_mod
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.73x1.98mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1385 Scripted version of SOP-4 footprint for isolators
  Package_SO.pretty/SOP-16_4.55x10.3mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-16_7.5x10.4mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-4_4.4x2.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-4_4.4x2.8mm_P1.27mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1380 Scripted version of MSOP-16 footprints
  Package_SO.pretty/MSOP-16-1EP_3x4mm_P0.5mm_EP1.65x2.85mm.kicad_mod
  Package_SO.pretty/MSOP-16-1EP_3x4mm_P0.5mm_EP1.65x2.85mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-16_3x4mm_P0.5mm.kicad_mod
Labels: Enhancement, ReadyForReview

#1386 Scripted sop-4 and sop-18 footpritns
  Package_SO.pretty/SOP-18_7.0x12.5mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-18_7x12.5mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOP-4_3.8x4.1mm_P2.54mm.kicad_mod
Labels: Enhancement, Pending reviewer

#1388 add 9 mm Alpha vertical pots
  Potentiometer_THT.pretty/Potentiometer_Alpha_RD901F-40-00D_Single_Vertical.kicad_mod
  Potentiometer_THT.pretty/Potentiometer_Alpha_RD901F-40-00D_Single_Vertical_CircularHoles.kicad_mod
  Potentiometer_THT.pretty/Potentiometer_Alpha_RD902F-40-00D_Dual_Vertical.kicad_mod
  Potentiometer_THT.pretty/Potentiometer_Alpha_RD902F-40-00D_Dual_Vertical_CircularHoles.kicad_mod
Labels: Addition, Pending changes

#1421 Add reverse mount 18.4x8mm TSOP-I-32
  Package_SO.pretty/TSOP-I-32_18.4x8mm_P0.5mm_Reverse.kicad_mod
Labels: Addition, Pending reviewer

#1428 Remove copper layer from paste (stencil) pads
  Package_TO_SOT_SMD.pretty/Vishay_PowerPAK_SC70-6L_Single.kicad_mod
Labels: Bug

#1414 Create missing Infineon MLPQ-48 footprints
  Package_DFN_QFN.pretty/Infineon_MLPQ-48-1EP_7x7mm_P0.5mm_EP5.55x5.55mm.kicad_mod
Labels: Addition

#1353 add Analog CP-16-22 LFCSP-16-1EP footprint
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
Labels: Addition, ReadyForReview

#1437 Transform jumpers into graphical polygons
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged2Bar_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged2Bar_RoundedPad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged_RoundedPad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_Pad1.0x1.5mm_NumberLabels.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_RoundedPad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_RoundedPad1.0x1.5mm_NumberLabels.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_Pad1.0x1.5mm_NumberLabels.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_RoundedPad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_RoundedPad1.0x1.5mm_NumberLabels.kicad_mod
Labels: Enhancement

#1436 Add Myrra EF20 footprint
  Transformer_THT.pretty/Transformer_Myrra_EF20_7408x.kicad_mod
Labels: Addition

#1441 Package_SO: Add a new HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mas…
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.4x3.7mm.kicad_mod
Labels: Addition

#1440 Use parent FP zone connection on rect pads
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged2Bar_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-2_P1.3mm_Bridged_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged12_Pad1.0x1.5mm_NumberLabels.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_Pad1.0x1.5mm.kicad_mod
  Jumper.pretty/SolderJumper-3_P1.3mm_Bridged2Bar12_Pad1.0x1.5mm_NumberLabels.kicad_mod
Labels: Bug
