Repository KiCad/kicad-footprints, pull requests merged in 2020-03, with the labels that each got.

#1996 TI NDQ
  Package_TO_SOT_SMD.pretty/Texas_NDQ.kicad_mod
Labels: Addition, Pending reviewer

#1990 Add Lumex SML-LX0303SIUPGUSB
  LED_SMD.pretty/LED_Lumex_SML-LX0303SIUPGUSB.kicad_mod
Labels: Addition

#2128 Add scripted footprints for castellated two terminal fuses
  Fuse.pretty/Fuse_0603_1608Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_0805_2012Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1206_3216Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1210_3225Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1806_4516Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1812_4532Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2010_5025Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2512_6332Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2816_7142Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2920_7451Metric_Castellated.kicad_mod
Labels: Addition, Pending reviewer

#1964 Added footprint for lightpipe Mentor Components 1275-x00x.
  OptoDevice.pretty/Lightpipe_Mentor_1275.x00x.kicad_mod
Labels: Addition, Pending reviewer

#1953 Fix Amphenol RJHSE dimensions
  Connector_RJ.pretty/RJ45_Amphenol_RJHSE5380-08.kicad_mod
  Connector_RJ.pretty/RJ45_Amphenol_RJHSE5380.kicad_mod
  Connector_RJ.pretty/RJ45_Amphenol_RJHSE538X.kicad_mod
Labels: Bug, Pending reviewer

#1948 Correct polarity of Yuji 5730 led
  LED_SMD.pretty/LED_Yuji_5730.kicad_mod
Labels: Bug, Pending reviewer, Question

#1966 Filter: Add 1FPxx - EMI filter
  Filter.pretty/Filter_FILTERCON_1FPxx.kicad_mod
Labels: Addition

#1638 Relay: Add Panasonic AD11 Form A
  Relay_THT.pretty/Relay_1P1T_NO_10x24x18.8mm_Panasonic_ADW11xxxxW_THT.kicad_mod
Labels: Addition

#2123 Create Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD.kicad_mod
Labels: Addition

#2124 Create Converter_DCDC_TRACO_THD_15-xxxxWIN_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_TRACO_THD_15-xxxxWIN_THT.kicad_mod
Labels: Addition, Pending reviewer

#2107 Inductors Choke Schaffner - wrong manufacturer name and pin spacings
  Inductor_THT.pretty/Choke_Schaffner_RN102-04-14.0x14.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN112-04-17.7x17.1mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN114-04-22.5x21.5mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN116-04-22.5x21.5mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN122-04-28.0x27.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN142-04-33.1x32.5mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN143-04-33.1x32.5mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN152-04-43.0x41.8mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN202-04-8.8x18.2mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN204-04-9.0x14.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN212-04-12.5x18.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN214-04-15.5x23.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN216-04-15.5x23.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN218-04-12.5x18.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN222-04-18.0x31.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN232-04-18.0x31.0mm.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN242-04-18.0x31.0mm.kicad_mod
Labels: Bug, Enhancement, Pending reviewer

#2138 Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD adjusted pad sizes to IPC-735…
  Converter_DCDC.pretty/Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD.kicad_mod
Labels: Bug, Enhancement

#2110 Add USB Micro-B connector Amphenol 10104110
  Connector_USB.pretty/USB_Micro-B_Amphenol_10104110_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#2139 Fix SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm naming
  Package_DFN_QFN.pretty/SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm_EP1.8x1.8mm.kicad_mod
  Package_DFN_QFN.pretty/SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm_EP1.8x1.8mm_ThermalVias.kicad_mod
Labels: Bug

#2127 Add switch C&K JS202011JCQN
  Button_Switch_SMD.pretty/SW_DPDT_CK_JS202011JCQN.kicad_mod
Labels: Addition, Pending reviewer

#2052 Added Omron B3FS tactile switch series.
  Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-100xP.kicad_mod
  Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-101xP.kicad_mod
  Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-105xP.kicad_mod
Labels: Addition, Pending reviewer

#2141 added ESP32-S2 SoC Module
  RF_Module.pretty/ESP32-S2-WROVER.kicad_mod
Labels: Addition

#2134 Added footprint for CUI CMT-8504-100-SMT
  Buzzer_Beeper.pretty/MagneticBuzzer_CUI_CMT-8504-100-SMT.kicad_mod
Labels: Addition

#2122 Create Molex_Pico-SPOX_87437-1443_1x14-P1.5mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_Pico-SPOX_87437-1443_1x14-P1.5mm_Vertical.kicad_mod
Labels: Addition, Pending reviewer

#2112 Connector_BarrelJack: Add CLIFF FC681465S DC socket
  Connector_BarrelJack.pretty/BarrelJack_CLIFF_FC681465S_SMT_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#2097 Add USB-B connector Lumberg 2411 02
  Connector_USB.pretty/USB_B_Lumberg_2411_02_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#2157 Add RJ45-Molex vertical connector footprint
  Connector_RJ.pretty/RJ45_Molex_0855135013_Vertical.kicad_mod
Labels: Addition

#2126 Adds Connector RJ11 Connfly DS1133-S4
  Connector_RJ.pretty/RJ14_Connfly_DS1133-S4_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#2140 Converter dcdc traco thd 15 xxxx win tht fixes
  Converter_DCDC.pretty/Converter_DCDC_TRACO_THD_15-xxxxWIN_THT.kicad_mod
Labels: Bug

#2154 Add Murata 78250JC
  Transformer_SMD.pretty/Transformer_Murata_78250JC.kicad_mod
Labels: Addition

#2161 Small fixes on some USB connectors
  Connector_USB.pretty/USB3_A_Plug_Wuerth_692112030100_Horizontal.kicad_mod
  Connector_USB.pretty/USB_A_CNCTech_1001-011-01101_Horizontal.kicad_mod
Labels: Enhancement, Pending reviewer

#2118 Create RJ45_Wuerth_7499111446_Horizontal.kicad_mod
  Connector_RJ.pretty/RJ45_Wuerth_7499111446_Horizontal.kicad_mod
Labels: Addition, Pending reviewer

#2116 Amphenol m8 s 03 pmmr sf8001
  Connector_Amphenol.pretty/Amphenol_M8S-03PMMR-SF8001.kicad_mod
  fp-lib-table
Labels: Addition, Pending reviewer

#2160 Added Wuerth 614004134726 USB-A socket
  Connector_USB.pretty/USB_A_Wuerth_614004134726_Horizontal.kicad_mod
Labels: Addition

#2159 Added TDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.38mm package for MAX17620
  Package_DFN_QFN.pretty/TDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.38mm.kicad_mod
Labels: Addition, Pending reviewer

#2119 Create TE_5767171-1
  Connector_TE-Connectivity.pretty/TE_5767171-1_2x19_P0.635mm_Vertical.kicad_mod
Labels: Addition, Pending reviewer

#2104 Restore PLCC-32 THT socket footprint
  Package_LCC.pretty/PLCC-32_THT-Socket.kicad_mod
Labels: Addition, Pending reviewer

#2068 fixed THT -> SMD and NXE2 -> NXEx
  Converter_DCDC.pretty/Converter_DCDC_muRata_NXE2SxxxxMC_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_muRata_NXExSxxxxMC_SMD.kicad_mod
Labels: Bug

#2173 Fix ltm4637 fp names
  Package_BGA.pretty/Linear_BGA-133_15.0x15.0mm_Layout12x12_P1.27mm.kicad_mod
  Package_LGA.pretty/Linear_LGA-133_15.0x15.0mm_Layout12x12_P1.27mm.kicad_mod
Labels: Enhancement

#2179 Close SOT-343 handsoldering courtyard
  Package_TO_SOT_SMD.pretty/SOT-343_SC-70-4_Handsoldering.kicad_mod
Labels: Bug

#2180 Removed pad numbers from paste only pads in LED_SMD library
  LED_SMD.pretty/LED_Cree-XB.kicad_mod
  LED_SMD.pretty/LED_Cree-XH.kicad_mod
  LED_SMD.pretty/LED_Cree-XHP35.kicad_mod
  LED_SMD.pretty/LED_Cree-XHP50_12V.kicad_mod
  LED_SMD.pretty/LED_Cree-XHP50_6V.kicad_mod
  LED_SMD.pretty/LED_Cree-XHP70_12V.kicad_mod
  LED_SMD.pretty/LED_Cree-XHP70_6V.kicad_mod
  LED_SMD.pretty/LED_Cree-XP-G.kicad_mod
  LED_SMD.pretty/LED_Cree-XP.kicad_mod
Labels: Enhancement

#1124 Connector PCB Edge: create Mini PCIe sockets
  Connector_PCBEdge.pretty/BUS_PCI_Express_Mini.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCI_Express_Mini_Dual.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCI_Express_Mini_Full.kicad_mod
  Connector_PCBEdge.pretty/BUS_PCI_Express_Mini_Half.kicad_mod
Labels: Addition, Pending changes
