Repository KiCad/kicad-footprints, pull requests merged in 2020-06, with the labels that each got.

#2268 Add Harwin S1941-46R spring contact
  Connector.pretty/SpringContact_Harwin_S1941-46R.kicad_mod
Labels: Addition

#2247 Add DFN-8_1EP_2x2mm_P0.5mm_EP0.9x1.6mm
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.6mm.kicad_mod
Labels: Addition

#2296 SMD Inductor: TracoPower TCK-047
  Inductor_SMD.pretty/L_TracoPower_TCK-047_5.2x5.8mm.kicad_mod
Labels: Addition, Pending changes

#2240 Fix F.Paste of Quectel BC66
  RF_GSM.pretty/Quectel_BC66.kicad_mod
Labels: Bug, Ready for review

#2059 Added NHD-C0220BiZ footprint
  Display.pretty/NHD-C0220BiZ.kicad_mod
Labels: Addition, Re-push, Ready for review

#1680 Infineon GAN footprints
  Package_SO.pretty/Infineon_PG-DSO-20-85.kicad_mod
  Package_SO.pretty/Infineon_PG-DSO-20-85_ThermalVias.kicad_mod
  Package_SO.pretty/Infineon_PG-DSO-20-87.kicad_mod
  Package_SON.pretty/Infineon_PG-LSON-8-1.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-3.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-3_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#2003 Added Abracon APAES868R8060C16-T
  RF_Antenna.pretty/Abracon_APAES868R8060C16-T.kicad_mod
Labels: Addition, Ready for review
