Repository KiCad/kicad-footprints, pull requests merged in 2020-10, with the labels that each got.

#2502 MP2303 Footprint, Generated by: IPC gullwing generator
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.62x3.51mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.62x3.51mm_ThermalVias.kicad_mod
Labels: Addition

#1590 Added Sipeed M1
  Module.pretty/Sipeed-M1.kicad_mod
Labels: Addition, Pending changes

#1792 Fix pad sizes of Taiyo Yuden NR series SMD inductors
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-20xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-24xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-30xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-40xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-50xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-60xx.kicad_mod
  Inductor_SMD.pretty/L_Taiyo-Yuden_NR-80xx.kicad_mod
Labels: Bug, Enhancement

#1965 Add Buzzer_Murata_PKLCS1212Exxxx-R1 series
  Buzzer_Beeper.pretty/Buzzer_Murata_PKLCS1212E.kicad_mod
  Buzzer_Beeper.pretty/Buzzer_Murata_PKMCS0909E.kicad_mod
Labels: Addition

#1698 Add Lumex SML-LX0404SIUPGUSB
  LED_SMD.pretty/LED_Lumex_SML-LX0404SIUPGUSB.kicad_mod
Labels: Addition

#1749 Inductor_SMD: Add Vishay IFSC-1515AH Low Profile, High Current Inductors
  Inductor_SMD.pretty/L_Vishay_IFSC-1515AH_4x4x1.8mm.kicad_mod
Labels: Addition

#2495 Chip molded footprint cleanup
  Diode_SMD.pretty/D_01005_0402Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_0201_0603Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_0402_1005Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_0603_1608Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_0805_2012Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_1206_3216Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_1210_3225Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_1812_4532Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_2010_5025Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_2114_3652Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_2512_6332Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_2816_7142Metric.kicad_mod
  Diode_SMD.pretty/D_2816_7142Metric_Castellated.kicad_mod
  Diode_SMD.pretty/D_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
  Diode_SMD.pretty/D_3220_8050Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_0402_1005Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_0603_1608Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_0805_2012Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1206_3216Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1210_3225Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_1812_4532Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2010_5025Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2512_6332Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2816_7142Metric.kicad_mod
  Fuse.pretty/Fuse_2816_7142Metric_Castellated.kicad_mod
  Fuse.pretty/Fuse_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
  Fuse.pretty/Fuse_2920_7451Metric_Castellated.kicad_mod
  Inductor_SMD.pretty/L_1806_4516Metric.kicad_mod
  Inductor_SMD.pretty/L_1806_4516Metric_Pad1.45x1.90mm_HandSolder.kicad_mod
  Inductor_SMD.pretty/L_1806_4516Metric_Pad1.57x1.80mm_HandSolder.kicad_mod
  Inductor_SMD.pretty/L_2816_7142Metric.kicad_mod
  Inductor_SMD.pretty/L_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
  LED_SMD.pretty/LED_0201_0603Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_0402_1005Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_0603_1608Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_0805_2012Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_1206_3216Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_1210_3225Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_1812_4532Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_2010_5025Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_2512_6332Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_2816_7142Metric.kicad_mod
  LED_SMD.pretty/LED_2816_7142Metric_Castellated.kicad_mod
  LED_SMD.pretty/LED_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
Labels: Enhancement
