Repository KiCad/kicad-footprints, pull requests merged in 2020-02, with the labels that each got.

#2011 Added QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.
  Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#1491 add Ninigi RJ45GE connector
  Connector_RJ.pretty/RJ45_Ninigi_GE.kicad_mod
Labels: Addition, Ready for review

#2067 Added Johanson 2450AT18x100 and 2450AT43F0100.
  RF_Antenna.pretty/Johanson_2450AT18x100.kicad_mod
  RF_Antenna.pretty/Johanson_2450AT43F0100.kicad_mod
Labels: Addition

#1418 add DS1095-WNR0
  Connector_USB.pretty/USB_A_CONNFLY_DS1095-WNR0.kicad_mod
Labels: Addition, Pending changes

#1659 Added 9V battery holder BA9VPC made by MPD
  Battery.pretty/BatteryHolder_MPD_BA9VPC_1xPP3.kicad_mod
Labels: Addition, Pending changes

#1552 Add Texas_QFN-41_10x16mm
  Package_DFN_QFN.pretty/Texas_QFN-41_10x16mm.kicad_mod
Labels: Addition, Ready for review

#1600 Footprint for Ublox zed
  RF_GPS.pretty/ublox_ZED.kicad_mod
Labels: Addition, Question, Ready for review

#1577 Solder wire pad 1x01 SMD 1x2mm
  Connector_Wire.pretty/SolderWirePad_1x01_SMD_1x2mm.kicad_mod
Labels: Addition, Ready for review

#2050 Add SMA_Wurth_60312002114503_Vertical.
  Connector_Coaxial.pretty/SMA_Wurth_60312002114503_Vertical.kicad_mod
Labels: Addition

#2049 Add QFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm footprint.
  Package_DFN_QFN.pretty/TQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
Labels: Addition

#2077 Hvqfn 24
  Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Addition

#2084 Addition of footprint for JTD series of DC-DC Converters from XP Power
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER_JTDxxxxxxx_THT.kicad_mod
Labels: Addition, Pending changes

#2092 Add JTD DC-DC COnverter Footprint (continuation from PR #2084)
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER_JTDxxxxxxx_THT.kicad_mod
Labels: Bug

#2085 Addition of XP Power RPA60-FW Series of DC-DC Converters
  Converter_DCDC.pretty/Converter_DCDC_RECOM_RPA60-xxxxSFW.kicad_mod
Labels: Addition

#2090 Added TSSOP variants as specified in JEDEC MO-153.
  Package_SO.pretty/TSSOP-14_4.4x5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-16_4.4x5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-20_4.4x5mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-20_4.4x6.5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-24_4.4x5mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-24_4.4x6.5mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-24_4.4x7.8mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-24_6.1x7.8mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-28_4.4x7.8mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-28_4.4x9.7mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-28_6.1x7.8mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-28_6.1x9.7mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-28_8x9.7mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-30_4.4x7.8mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-30_6.1x9.7mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-32_4.4x6.5mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-32_6.1x11mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-32_8x11mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-36_4.4x7.8mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-36_4.4x9.7mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-36_6.1x12.5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-36_6.1x7.8mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-36_6.1x9.7mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-36_8x12.5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-36_8x9.7mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-38_4.4x9.7mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-38_6.1x12.5mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-40_6.1x11mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-40_6.1x14mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-40_8x11mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-40_8x14mm_P0.65mm.kicad_mod
  Package_SO.pretty/TSSOP-44_4.4x11mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-44_6.1x11mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-48_4.4x9.7mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-48_6.1x12.5mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-48_6.1x9.7mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-48_8x12.5mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-48_8x9.7mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-50_4.4x12.5mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-52_6.1x11mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-52_8x11mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-56_6.1x12.5mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-56_6.1x14mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-56_8x12.5mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-56_8x14mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-60_8x12.5mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-64_6.1x14mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-64_6.1x17mm_P0.5mm.kicad_mod
  Package_SO.pretty/TSSOP-64_8x14mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-68_8x14mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-80_6.1x17mm_P0.4mm.kicad_mod
  Package_SO.pretty/TSSOP-8_4.4x3mm_P0.65mm.kicad_mod
Labels: Addition, Enhancement

#2083 Addition of Texas Instruments DC-DC Converter Modules PTN78000 (1.5A)…
  Converter_DCDC.pretty/Converter_DCDC_Texas_PTN78000_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_Texas_PTN78020_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_Texas_PTN78060_THT.kicad_mod
Labels: Addition

#1995 Added footprint for ST VL53L1x distance sensor
  Sensor_Distance.pretty/ST_VL53L1x.kicad_mod
  fp-lib-table
Labels: Addition

#1988 Add TQFN-48 7x7mm
  Package_DFN_QFN.pretty/TQFN-48-1EP_7x7mm_P0.5mm_EP5.1x5.1mm.kicad_mod
  Package_DFN_QFN.pretty/TQFN-48-1EP_7x7mm_P0.5mm_EP5.1x5.1mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#2101 Add WQFN-42-1EP_3.5x9mm_P0.5mm_EP2.05x7.55mm
  Package_DFN_QFN.pretty/WQFN-42-1EP_3.5x9mm_P0.5mm_EP2.05x7.55mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-42-1EP_3.5x9mm_P0.5mm_EP2.05x7.55mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#2102 Generate MSOP-8_3x3mm_P0.65mm using fine pitch definitions
  Package_SO.pretty/MSOP-8_3x3mm_P0.65mm.kicad_mod
Labels: Enhancement, Pending reviewer

#2103 Generate P0.65mm gullwing packages using fine pitch defs
  Package_QFP.pretty/PQFP-100_14x20mm_P0.65mm.kicad_mod
  Package_QFP.pretty/PQFP-144_28x28mm_P0.65mm.kicad_mod
  Package_QFP.pretty/PQFP-160_28x28mm_P0.65mm.kicad_mod
Labels: Enhancement, Pending reviewer

#2100 Add footprints for Cyntec DC/DC modules MUN12AD0x-SH
  Converter_DCDC.pretty/Converter_DCDC_Cyntec_MUN12AD01-SH.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_Cyntec_MUN12AD03-SH.kicad_mod
Labels: Addition, Ready for review

#2105 Lightpipe_LPF-C012303S is not virtual
  OptoDevice.pretty/Lightpipe_LPF-C012303S.kicad_mod
Labels: Bug, Pending reviewer

#2079 Fixed wrong pin spacing in Choke_Schaffner_RN202 and missing pins in Converter_DCDC_XP_POWER-ITxxxxxS_THT
  Converter_DCDC.pretty/Converter_DCDC_XP_POWER-ITxxxxxS_THT.kicad_mod
  Inductor_THT.pretty/Choke_Schaffner_RN202-04-8.8x18.2mm.kicad_mod
Labels: Bug

#2108 Renaming of Texas PTN Series footprints to generic module names
  Module.pretty/Texas_EUK_R-PDSS-T7_THT.kicad_mod
  Module.pretty/Texas_EUS_R-PDSS-T5_THT.kicad_mod
  Module.pretty/Texas_EUW_R-PDSS-T7_THT.kicad_mod
Labels: Enhancement
