Repository KiCad/kicad-footprints, pull requests merged in 2020-09, with the labels that each got.

#2233 Adds HSOP-8 package in 2.3x2.3mm EP variety
  Package_SO.pretty/HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.3x2.3mm.kicad_mod
  Package_SO.pretty/HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.3x2.3mm_ThermalVias.kicad_mod
Labels: Addition

#2434 added footprint Texas_B3QFN-14-1EP_5x5.5mm_P0.65mm
  Package_DFN_QFN.pretty/Texas_B3QFN-14-1EP_5x5.5mm_P0.65mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_B3QFN-14-1EP_5x5.5mm_P0.65mm_ThermalVia.kicad_mod
Labels: Addition

#2308 Add Senseair S8 CO2 sensor
  Sensor.pretty/Senseair_S8_Down.kicad_mod
  Sensor.pretty/Senseair_S8_Up.kicad_mod
Labels: Addition, Pending changes

#2453 Wrong links to datasheets corrected for Panasonic lithium batteries
  Battery.pretty/Battery_Panasonic_CR1025-VSK_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR1220-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR1632-V1AN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2025-V1AK_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2032-VS1N_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2354-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2450-VAN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR2477-VCN_Vertical_CircularHoles.kicad_mod
  Battery.pretty/Battery_Panasonic_CR3032-VCN_Vertical_CircularHoles.kicad_mod
Labels: Enhancement

#2365 WLCSP-16_1.409x1.409mm_P0.35mm
  Package_CSP.pretty/WLCSP-16_1.409x1.409mm_P0.35mm.kicad_mod
Labels: Addition

#2448 fix BGA-132_12x18mm_Layout11x17_P0.5mm
  Package_BGA.pretty/BGA-132_12x18mm_Layout11x17_P1.0mm.kicad_mod
Labels: Bug

#2315 Add SSOP-16_5.3x6.2mm_P0.65mm from https://github.com/pointhi/kicad-f…
  Package_SO.pretty/SSOP-16_5.3x6.2mm_P0.65mm.kicad_mod
Labels: Addition

#2442 add TSSOP-24-1EP
  Package_SO.pretty/TSSOP-24-1EP_4.4x7.8mm_P0.65mm_EP3.2x5mm.kicad_mod
Labels: Addition

#2350 Added LQFN-48 package with 16 centered ground pins and thermal vias
  Package_DFN_QFN.pretty/NXP_LQFN-48-1EP_7x7mm_P0.5mm_EP3.5x3.5mm_16xMask0.45x0.45.kicad_mod
  Package_DFN_QFN.pretty/NXP_LQFN-48-1EP_7x7mm_P0.5mm_EP3.5x3.5mm_16xMask0.45x0.45_ThermalVias.kicad_mod
Labels: Addition

#2457 Add WDFN-8 from https://github.com/pointhi/kicad-footprint-generator/…
  Package_DFN_QFN.pretty/WDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.2mm.kicad_mod
Labels: Addition

#2264 Add Buzzer_Beeper/Indicator_PUI_AI-1440-TWT-24V-2-R
  Buzzer_Beeper.pretty/Indicator_PUI_AI-1440-TWT-24V-2-R.kicad_mod
Labels: Addition, Pending changes

#2451 QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#2447 Added OnSemi custom WDFN6 footprint
  Package_DFN_QFN.pretty/WDFN-6-2EP_4.0x2.6mm_P0.65mm.kicad_mod
Labels: Addition

#2462 Create SSOP-48_5.3x12.8mm_P0.5mm.kicad_mod
  Package_SO.pretty/SSOP-48_5.3x12.8mm_P0.5mm.kicad_mod
Labels: Addition

#2469 Add TDFN-8-1EP_3x2mm_P0.5mm_EP1.4x1.4mm
  Package_DFN_QFN.pretty/TDFN-8-1EP_3x2mm_P0.5mm_EP1.4x1.4mm.kicad_mod
Labels: Addition

#2437 Added BGA-200 pitch 0.80x0.65 mm for LPDDR4/4X SDRAM.
  Package_BGA.pretty/BGA-200_10.0x14.5mm_Layout12x22_P0.80x0.65mm.kicad_mod
Labels: Addition

#2458 Package_DFN_QFN: Add UFQFPN-32 packages
  Package_DFN_QFN.pretty/UFQFPN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm.kicad_mod
  Package_DFN_QFN.pretty/UFQFPN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm_ThermalVias.kicad_mod
Labels: Addition

#2307 Added WLCSP-8 package for Adesto Flash memory AT25SL321-UUE-T
  Package_CSP.pretty/WLCSP-8_1.551x2.284mm_P0.5mm.kicad_mod
Labels: Addition, Scripting required

#2226 Add Analog/Linear DD footprints
  Package_DFN_QFN.pretty/DFN-8-1EP_3x3mm_P0.5mm_EP1.65x2.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x3mm_P0.5mm_EP1.65x2.38mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#2356 add RAK Wireless RAK4200 LoRa module footprint
  RF_Module.pretty/RAK4200.kicad_mod
Labels: Addition

#2438 Sensor_Audio: Add LGA footprint for Knowles SPH0641LU4H-1
  Sensor_Audio.pretty/Knowles_LGA-5_3.5x2.65mm.kicad_mod
Labels: Addition, Pending changes

#2460 add HVSSOP-10, generated from scripts, https://github.com/pointhi/kic…
  Package_SO.pretty/HVSSOP-10-1EP_3x3mm_P0.5mm_EP1.57x1.88mm.kicad_mod
  Package_SO.pretty/HVSSOP-10-1EP_3x3mm_P0.5mm_EP1.57x1.88mm_ThermalVias.kicad_mod
Labels: Addition

#2430 Added 3D for balun Johanson 0900PC15J0013
  RF_Converter.pretty/Balun_Johanson_0900PC15J0013.kicad_mod
Labels: Addition

#2202 QFN-64 with 5.2x5.2mm exposed pad.
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP5.2x5.2mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP5.2x5.2mm_ThermalVias.kicad_mod
Labels: Addition

#2323 Add RAK Wireless RAK811 LoRa module footprint
  RF_Module.pretty/RAK811.kicad_mod
Labels: Addition

#2072 Regenerate missed FPs / #422
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.3x2.3mm.kicad_mod
  Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.3x2.3mm_ThermalVias.kicad_mod
  Package_CSP.pretty/LFCSP-8-1EP_3x3mm_P0.5mm_EP1.45x1.74mm.kicad_mod
  Package_CSP.pretty/LFCSP-WD-10-1EP_3x3mm_P0.5mm_EP1.64x2.38mm.kicad_mod
  Package_CSP.pretty/LFCSP-WD-10-1EP_3x3mm_P0.5mm_EP1.64x2.38mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/OnSemi_VCT-28_3.5x3.5mm_P0.4mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.3x4.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.3x4.3mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-46-1EP_5x6mm_P0.4mm_EP2.8x3.8mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-46-1EP_5x6mm_P0.4mm_EP2.8x3.8mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm_ThermalVias.kicad_mod
Labels: Bug

#2300 Replace TQFP-48_7x7mm_P0.5mm with scripted version
  Package_QFP.pretty/TQFP-48_7x7mm_P0.5mm.kicad_mod
Labels: Addition

#2475 Change sot563 pad y dimension to 0.34mm to make sure the pad to pad clearance
  Package_TO_SOT_SMD.pretty/SOT-563.kicad_mod
Labels: Enhancement, Pending reviewer

#2189 Added VQFN-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-48-1EP_7x7mm_P0.5mm_EP4.1x4.1mm_ThermalVias.kicad_mod
Labels: Addition

#2461 Add TSSOP16 variant with EP
  Package_SO.pretty/TSSOP-16-1EP_4.4x5mm_P0.65mm_EP3x3mm.kicad_mod
  Package_SO.pretty/TSSOP-16-1EP_4.4x5mm_P0.65mm_EP3x3mm_ThermalVias.kicad_mod
Labels: Addition

#1924 Adding Lattice_caBGA-756_27.0x27.0mm_Layout32x32_P0.8mm
  Package_BGA.pretty/Lattice_caBGA-756_27.0x27.0mm_Layout32x32_P0.8mm.kicad_mod
Labels: Addition

#1876 add LFCSP-8-1EP_3x3mm_P0.5mm_EP1.6x2.34mm
  Package_CSP.pretty/LFCSP-8-1EP_3x3mm_P0.5mm_EP1.6x2.34mm.kicad_mod
  Package_CSP.pretty/LFCSP-8-1EP_3x3mm_P0.5mm_EP1.6x2.34mm_ThermalVias.kicad_mod
Labels: Addition

#1943 Quectel BC95
  RF_GSM.pretty/Quectel_BC95.kicad_mod
Labels: Addition

#1763 add Heatsink Fischer FK24413DPAK
  Heatsink.pretty/Heatsink_Fischer_FK24413DPAK_23x13mm.kicad_mod
Labels: Addition

#1926 Add Fuseholder for littelfuse nano2
  Fuse.pretty/Fuseholder_Littelfuse_Nano2_154x.kicad_mod
Labels: Addition, Pending changes

#2468 HTSSOP-44_6.1x14mm_P0.635mm_TopEP4.14x7.01mm
  Package_SO.pretty/HTSSOP-44_6.1x14mm_P0.635mm_TopEP4.14x7.01mm.kicad_mod
Labels: Addition

#1743 Te ms5525 dso
  Sensor_Pressure.pretty/TE_MS5525DSO-DBxxxyS.kicad_mod
Labels: Addition

#2378 Add BM78SPPS5XC2 bluetooth module footprint
  RF_Module.pretty/BM78SPPS5XC2.kicad_mod
Labels: Addition

#1637 added DFN-14_1.35x3.5mm_P0.5mm
  Package_DFN_QFN.pretty/DFN-14_1.35x3.5mm_P0.5mm.kicad_mod
Labels: Addition

#1881 Add D_SOT-1289
  Package_TO_SOT_SMD.pretty/Nexperia_CFP15_SOT-1289.kicad_mod
Labels: Addition, Pending changes

#2191 Added Balun Johanson 0896BM15A0001, same as 5400BL15B050 with differe…
  RF_Converter.pretty/Balun_Johanson_0896BM15A0001.kicad_mod
Labels: Addition

#2439 Add script generated HVQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm
  Package_DFN_QFN.pretty/HVQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/HVQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm_ThermalVias.kicad_mod
Labels: Addition, Librarian

#2303 add HVQFN-40 from NXP
  Package_DFN_QFN.pretty/HVQFN-40-1EP_6x6mm_P0.5mm_EP4.1x4.1mm.kicad_mod
  Package_DFN_QFN.pretty/HVQFN-40-1EP_6x6mm_P0.5mm_EP4.1x4.1mm_ThermalVias.kicad_mod
Labels: Addition

#2481 Added TO-46-4 + ThermalShield for LM399
  Package_TO_SOT_THT.pretty/Analog_TO-46-4_ThermalShield.kicad_mod
Labels: Addition

#2482 Add OnSemi QRE1113 and Everlight ITR1201SR10AR
  OptoDevice.pretty/Everlight_ITR1201SR10AR.kicad_mod
  OptoDevice.pretty/OnSemi_CASE100AQ.kicad_mod
Labels: Addition

#2487 Fix L_1806 by reverting to previous version
  Inductor_SMD.pretty/L_1806_4516Metric.kicad_mod
  Inductor_SMD.pretty/L_1806_4516Metric_Pad1.45x1.20mm_HandSolder.kicad_mod
  Inductor_SMD.pretty/L_1806_4516Metric_Pad1.57x1.80mm_HandSolder.kicad_mod
Labels: Bug

#2293 Add Oscillator_SMD_Fox_FT5H_5.0x3.2mm
  Oscillator.pretty/Oscillator_SMD_Fox_FT5H_5.0x3.2mm.kicad_mod
Labels: Addition

#1772 Sumida c75
  Inductor_SMD.pretty/L_Sumida_CR75.kicad_mod
Labels: Addition

#2265 Add AC/DC converters Recom RAC20-xxSK and RAC20-xxDK
  Converter_ACDC.pretty/Converter_ACDC_Recom_RAC20-xxDK_THT.kicad_mod
  Converter_ACDC.pretty/Converter_ACDC_Recom_RAC20-xxSK_THT.kicad_mod
Labels: Addition

#2444 EA DOGM128 and DOGL128 displays added
  Display.pretty/EA_DOGL128-6.kicad_mod
  Display.pretty/EA_DOGM128-6.kicad_mod
Labels: Addition

#1880 Add D_SOD-123W
  Diode_SMD.pretty/Nexperia_CFP3_SOD-123W.kicad_mod
Labels: Addition, Pending changes

#2422 Rgb THT led URL fixes
  LED_THT.pretty/LED_D5.0mm-4_RGB.kicad_mod
  LED_THT.pretty/LED_D5.0mm-4_RGB_Staggered_Pins.kicad_mod
  LED_THT.pretty/LED_D5.0mm-4_RGB_Wide_Pins.kicad_mod
Labels: Enhancement

#2111 Create Texas_RUK_S-PWQFN-N20_EP_3x3_Pitch0.4mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm_ThermalVias.kicad_mod
Labels: Addition

#1954 Added footprint for BelFuse SI-60062-F.
  Connector_RJ.pretty/RJ45_Bel_SI-60062-F.kicad_mod
Labels: Addition

#2186 Added OnSemi_SIP-38-6EP-9x7mm_P0.65mm_EP0.95x0.95mm
  Package_DFN_QFN.pretty/OnSemi_SIP-38-6EP-9x7mm_P0.65mm_EP1.2x1.2mm.kicad_mod
Labels: Addition

#2490 Package_DFN_QFN: Add VQFN-64-1EP_9x9mm_P0.5mm_EP5.4x5.4mm
  Package_DFN_QFN.pretty/VQFN-64-1EP_9x9mm_P0.5mm_EP5.4x5.4mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-64-1EP_9x9mm_P0.5mm_EP5.4x5.4mm_ThermalVias.kicad_mod
Labels: Addition

#2223 Add WSON-8 Package with 1.45 x 2.4mm Pad
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.45x2.4mm.kicad_mod
  Package_SON.pretty/Texas_S-PWSON-N8_EP1.45x2.4mm_ThermalVias.kicad_mod
Labels: Addition

#1372 Reverb Belton
  Audio_Module.pretty/Reverb_BTDR-1H.kicad_mod
  Audio_Module.pretty/Reverb_BTDR-1V.kicad_mod
  fp-lib-table
Labels: Abandoned, Addition, Librarian, Pending changes

#2493 Reverb_BTDR-1H/V: minor silkscreen improvement
  Audio_Module.pretty/Reverb_BTDR-1H.kicad_mod
  Audio_Module.pretty/Reverb_BTDR-1V.kicad_mod
Labels: Enhancement

#2494 Make Texas_WSON-N8 variants non vendor specific
  Package_SON.pretty/WSON-8-1EP_3x3mm_P0.5mm_EP1.2x2mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x3mm_P0.5mm_EP1.2x2mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x3mm_P0.5mm_EP1.45x2.4mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_3x3mm_P0.5mm_EP1.45x2.4mm_ThermalVias.kicad_mod
Labels: Bug

#1884 Add RB1-125B8G1A RJ45 jack
  Connector_RJ.pretty/RJ45_UDE_RB1-125B8G1A.kicad_mod
Labels: Addition

#2410 Replace SOT-23 variants with scripted
  Package_TO_SOT_SMD.pretty/SOT-23-5.kicad_mod
  Package_TO_SOT_SMD.pretty/SOT-23-6.kicad_mod
  Package_TO_SOT_SMD.pretty/SOT-23-8.kicad_mod
Labels: Enhancement

#2412 Replace TSOT-23-5/6/8 with scripted
  Package_TO_SOT_SMD.pretty/TSOT-23-5.kicad_mod
  Package_TO_SOT_SMD.pretty/TSOT-23-6.kicad_mod
  Package_TO_SOT_SMD.pretty/TSOT-23-8.kicad_mod
Labels: Enhancement

#1692 Add QFN-12 footprint with 8 thermal vias
  Package_DFN_QFN.pretty/QFN-12-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-12-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
Labels: Addition

#2185 Added UQFN-20_3x3mm_P0.4mm without exposed pad
  Package_DFN_QFN.pretty/UQFN-20_3x3mm_P0.4mm.kicad_mod
Labels: Addition

#2212 Add Panasonic AQ-H series solid state relays, SSO-8-N7
  Package_SO.pretty/SSO-7-8_6.4x9.78mm_P2.54mm.kicad_mod
Labels: Addition

#592 CUI PD-30S connector.
  Connector.pretty/CUI_PD-30S.kicad_mod
  Connector.pretty/CUI_PD-30S_CircularHoles.kicad_mod
Labels: Addition

#2496 BC95 fix F.Paste
  RF_GSM.pretty/Quectel_BC95.kicad_mod
Labels: Enhancement

#2390 Add Raytac MDBT50Q Module
  RF_Module.pretty/Raytac_MDBT50Q.kicad_mod
Labels: Addition

#2500 Replace WSON-8_4x4mm_P0.8mm with generated one
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP2.6x3mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP2.6x3mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8_4x4mm_P0.8mm.kicad_mod
Labels: Bug

#1523 Murata SFECF
  Filter.pretty/Filter_Murata_SFECF-6.kicad_mod
  Filter.pretty/Filter_Murata_SFECF-6_HandSoldering.kicad_mod
Labels: Addition

#1446 Package_SO: Rename SOIJ-8_5.3x5.3mm_P1.27mm to SOIC-8W_5.3x5.3mm_P1.27mm
  Package_SO.pretty/SOIC-8W_5.3x5.3mm_P1.27mm.kicad_mod
Labels: Abandoned, Enhancement

#2228 Add footprint for Quectel L80 GPS module
  RF_GPS.pretty/Quectel_L80-R.kicad_mod
Labels: Addition

#2383 Added Diode_Bridge_Comchip_SCVB-L
  Diode_THT.pretty/Diode_Bridge_Comchip_SCVB-L.kicad_mod
Labels: Addition

#2109 Add LTC-4627Jx 7-segemnt displays
  Display_7Segment.pretty/LTC-4627Jx.kicad_mod
Labels: Addition

#2503 Add two more WSON-8-1EP_4x4mm_P0.8mm variants
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP1.98x3mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP1.98x3mm_ThermalVias.kicad_mod
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP2.2x3mm.kicad_mod
  Package_SON.pretty/WSON-8-1EP_4x4mm_P0.8mm_EP2.2x3mm_ThermalVias.kicad_mod
Labels: Addition

#1758 Add Cromatek 0.56in 7-segment display footprint
  Display_7Segment.pretty/D1X8K.kicad_mod
Labels: Addition

#2363 OnSemi_XDFN4-1EP_1.0x1.0mm_EP0.52x0.52mm.kicad_mod
  Package_DFN_QFN.pretty/OnSemi_XDFN4-1EP_1.0x1.0mm_EP0.52x0.52mm.kicad_mod
Labels: Addition

#1739 8devices Carambola2 footprint added
  Module.pretty/Carambola2.kicad_mod
Labels: Addition, Ready for review

#2018 WDFN-8-1EP_6x5mm_P1.27_EP4x3.4mm added.
  Package_DFN_QFN.pretty/WDFN-8-1EP_6x5mm_P1.27mm_EP3.4x4mm.kicad_mod
Labels: Addition, Scripting required

#1781 Added footprint for ERM19264 192x64 display module
  Display.pretty/ERM19264.kicad_mod
Labels: Addition

#2505 Remove emtpy string floating in space on L_TDK_SLF12575
  Inductor_SMD.pretty/L_TDK_SLF12575.kicad_mod
Labels: Bug

#2364 WLCSP-4-X1-WLB0909-4_0.890x0.890_P0.500mm
  Package_CSP.pretty/WLCSP-4-X1-WLB0909-4_0.89x0.89mm_P0.5mm.kicad_mod
Labels: Addition

#2488 LED SMD: Create Wurth 150141M173100
  LED_SMD.pretty/LED_RGB_Wuerth-PLCC4_3.2x2.8mm_150141M173100.kicad_mod
Labels: Addition

#2504 Create Infineon_LFBGA-292_17x17mm
  Package_BGA.pretty/Infineon_LFBGA-292_17x17mm_Layout20x20_P0.8mm_Ball0.5mm_Pad0.35.kicad_mod
Labels: Addition, Pending reviewer

#2169 Connector_JST: add XA (horizontal + vertical)
  Connector_JST.pretty/JST_XA_B02B-XASK-1-A_1x02_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B02B-XASK-1_1x02_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B03B-XASK-1-A_1x03_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B03B-XASK-1_1x03_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B04B-XASK-1-A_1x04_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B04B-XASK-1_1x04_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B05B-XASK-1-A_1x05_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B05B-XASK-1_1x05_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B06B-XASK-1-A_1x06_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B06B-XASK-1_1x06_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B07B-XASK-1-A_1x07_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B07B-XASK-1_1x07_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B08B-XASK-1-A_1x08_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B08B-XASK-1_1x08_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B09B-XASK-1-A_1x09_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B09B-XASK-1_1x09_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B10B-XASK-1-A_1x10_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B10B-XASK-1_1x10_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B11B-XASK-1-A_1x11_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B11B-XASK-1_1x11_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B12B-XASK-1-A_1x12_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B12B-XASK-1_1x12_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B13B-XASK-1-A_1x13_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B13B-XASK-1_1x13_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B14B-XASK-1-A_1x14_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B14B-XASK-1_1x14_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B15B-XASK-1-A_1x15_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B15B-XASK-1_1x15_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B18B-XASK-1_1x18_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B20B-XASK-1-A_1x20_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_B20B-XASK-1_1x20_P2.50mm_Vertical.kicad_mod
  Connector_JST.pretty/JST_XA_S02B-XASK-1N-BN_1x02_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S02B-XASK-1_1x02_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S03B-XASK-1N-BN_1x03_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S03B-XASK-1_1x03_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S04B-XASK-1N-BN_1x04_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S04B-XASK-1_1x04_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S05B-XASK-1N-BN_1x05_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S05B-XASK-1_1x05_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S06B-XASK-1N-BN_1x06_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S06B-XASK-1_1x06_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S07B-XASK-1N-BN_1x07_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S07B-XASK-1_1x07_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S08B-XASK-1N-BN_1x08_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S08B-XASK-1_1x08_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S09B-XASK-1N-BN_1x09_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S09B-XASK-1_1x09_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S10B-XASK-1N-BN_1x10_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S10B-XASK-1_1x10_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S11B-XASK-1N-BN_1x11_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S11B-XASK-1_1x11_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S12B-XASK-1N-BN_1x12_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S12B-XASK-1_1x12_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S13B-XASK-1N-BN_1x13_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S13B-XASK-1_1x13_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S14B-XASK-1N-BN_1x14_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/JST_XA_S14B-XASK-1_1x14_P2.50mm_Horizontal.kicad_mod
  Connector_JST.pretty/README.md
Labels: Addition

#2299 Add Quectel M95 GSM modem
  RF_GSM.pretty/Quectel_M95.kicad_mod
Labels: Addition

#2491 Fuseholder Keystone 3555-2
  Fuse.pretty/Fuseholder_Keystone_3555-2.kicad_mod
Labels: Addition

#2478 Added Kionix_LGA-12_2x2mm_P0.5mm_LayoutBorder2x4y.
  Package_LGA.pretty/Kionix_LGA-12_2x2mm_P0.5mm_LayoutBorder2x4y.kicad_mod
Labels: Addition
