Repository KiCad/kicad-footprints, pull requests merged in 2020-04, with the labels that each got.

#2178 Fix hole sizes in 2.54 mm headers.
  Module.pretty/Arduino_Nano.kicad_mod
  Module.pretty/Arduino_Nano_WithMountingHoles.kicad_mod
  Module.pretty/Arduino_UNO_R2.kicad_mod
  Module.pretty/Arduino_UNO_R2_WithMountingHoles.kicad_mod
  Module.pretty/Arduino_UNO_R3.kicad_mod
  Module.pretty/Arduino_UNO_R3_WithMountingHoles.kicad_mod
Labels: Bug

#2227 Added modified HTSSOP footprint for EP size for MAX482x ICs
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP2.85x4mm.kicad_mod
Labels: Addition

#2166 Fix relays
  Relay_THT.pretty/Relay_DPDT_Finder_30.22.kicad_mod
  Relay_THT.pretty/Relay_DPDT_Omron_G5V-2.kicad_mod
Labels: Bug, Enhancement

#2205 Fix ublox_NEO footprint missing paste on VCC pad 23
  RF_GPS.pretty/ublox_LEA.kicad_mod
  RF_GPS.pretty/ublox_MAX.kicad_mod
  RF_GPS.pretty/ublox_NEO.kicad_mod
Labels: Bug

#2055 Added USB_A_Molex_67643_Horizontal
  Connector_USB.pretty/USB_A_Molex_67643_Horizontal.kicad_mod
Labels: Addition

#2239 Fix F.Paste of SIMCom SIM800C
  RF_GSM.pretty/SIMCom_SIM800C.kicad_mod
Labels: Bug

#2238 Fuseholder for Littelfuse Nano2 series 157x
  Fuse.pretty/Fuseholder_Littelfuse_Nano2_157x.kicad_mod
Labels: Addition

#2237 Added Bourns SRU8028 SMD inductor.
  Inductor_SMD.pretty/L_Bourns-SRU8028_8.0x8.0mm.kicad_mod
Labels: Addition, Pending reviewer

#2245 Add Texas NS/PS packages
  Package_SO.pretty/SO-14_5.3x10.2mm_P1.27mm.kicad_mod
  Package_SO.pretty/SO-16_5.3x10.2mm_P1.27mm.kicad_mod
  Package_SO.pretty/SO-20_5.3x12.6mm_P1.27mm.kicad_mod
  Package_SO.pretty/SO-24_5.3x15mm_P1.27mm.kicad_mod
  Package_SO.pretty/SO-8_5.3x6.2mm_P1.27mm.kicad_mod
Labels: Addition, Enhancement

#2244 Fix Pin 1 Markers to fit with KLC (IPC suggestion)
  Package_DFN_QFN.pretty/DFN-10-1EP_2x3mm_P0.5mm_EP0.64x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.55x2.48mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-10-1EP_3x3mm_P0.5mm_EP1.75x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-10_2x2mm_P0.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_2x3mm_P0.45mm_EP0.64x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_3x3mm_P0.45mm_EP1.66x2.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_3x3mm_P0.5mm_EP2.05x2.86mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_3x4mm_P0.5mm_EP1.7x3.3mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_4x4mm_P0.5mm_EP2.66x3.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-12-1EP_4x4mm_P0.65mm_EP2.64x3.54mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-14-1EP_3x3mm_P0.4mm_EP1.78x2.35mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-14-1EP_3x4.5mm_P0.65mm_EP1.65x4.25mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-14-1EP_3x4.5mm_P0.65mm_EP1.65x4.25mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/DFN-14-1EP_3x4mm_P0.5mm_EP1.7x3.3mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-14-1EP_4x4mm_P0.5mm_EP2.86x3.6mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-16-1EP_3x4mm_P0.45mm_EP1.7x3.3mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-16-1EP_3x5mm_P0.5mm_EP1.66x4.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-16-1EP_4x5mm_P0.5mm_EP2.44x4.34mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-16-1EP_5x5mm_P0.5mm_EP3.46x4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-18-1EP_3x5mm_P0.5mm_EP1.66x4.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-18-1EP_4x5mm_P0.5mm_EP2.44x4.34mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-20-1EP_5x6mm_P0.5mm_EP3.24x4.24mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-22-1EP_5x6mm_P0.5mm_EP3.14x4.3mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-24-1EP_4x7mm_P0.5mm_EP2.64x6.44mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-32-1EP_4x7mm_P0.4mm_EP2.64x6.44mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-44-1EP_5x8.9mm_P0.4mm_EP3.7x8.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_2x2mm_P0.5mm_EP0.61x1.42mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_2x2mm_P0.65mm_EP1x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-6-1EP_3x3mm_P0.95mm_EP1.7x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.45mm_EP0.64x1.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP1.05x1.75mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_2x3mm_P0.5mm_EP0.61x2.2mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.45mm_EP1.66x1.36mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.36x1.46mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.3x1.5mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.75x1.45mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x3mm_P0.5mm_EP1.66x2.38mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_3x3mm_P0.65mm_EP1.55x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_4x4mm_P0.8mm_EP2.39x2.21mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_4x4mm_P0.8mm_EP2.5x3.6mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_6x5mm_P1.27mm_EP2x2mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8-1EP_6x5mm_P1.27mm_EP4x4mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-8_2x2mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/DFN-S-8-1EP_6x5mm_P1.27mm.kicad_mod
  Package_DFN_QFN.pretty/Diodes_UDFN-10_1.0x2.5mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/OnSemi_DFN-8_2x2mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/OnSemi_UDFN-8_1.2x1.8mm_P0.4mm.kicad_mod
  Package_DFN_QFN.pretty/Qorvo_DFN-8-1EP_2x2mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-12_2x3mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-8-1EP_3x2mm_P0.5mm_EP1.80x1.65mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-8-1EP_3x2mm_P0.5mm_EP1.80x1.65mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UDFN-10_1.35x2.6mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/UDFN-9_1.0x3.8mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/VDFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.7mm.kicad_mod
  Package_DFN_QFN.pretty/WDFN-8-1EP_2x2.2mm_P0.5mm_EP0.80x0.54.kicad_mod
  Package_DFN_QFN.pretty/WDFN-8_2x2mm_P0.5mm.kicad_mod
Labels: Enhancement, Pending reviewer

#2246 Fix hole size for Molex KK-254
  Connector_Molex.pretty/Molex_KK-254_AE-6410-02A_1x02_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-03A_1x03_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-04A_1x04_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-05A_1x05_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-06A_1x06_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-07A_1x07_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-08A_1x08_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-09A_1x09_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-10A_1x10_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-11A_1x11_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-12A_1x12_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-13A_1x13_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-14A_1x14_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-15A_1x15_P2.54mm_Vertical.kicad_mod
  Connector_Molex.pretty/Molex_KK-254_AE-6410-16A_1x16_P2.54mm_Vertical.kicad_mod
Labels: Bug, Pending reviewer
