Repository KiCad/kicad-footprints, pull requests merged in 2020-08, with the labels that each got.

#2287 Wuerth WP-THRBU REDCUBE THR connectors
  TerminalBlock_Wuerth.pretty/README.md
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650073_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650074_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650094_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650173_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650174_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650194_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74650195_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRBU_74655095_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRSH_74651173_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRSH_74651174_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRSH_74651175_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRSH_74651194_THR.kicad_mod
  TerminalBlock_Wuerth.pretty/Wuerth_REDCUBE-THR_WP-THRSH_74651195_THR.kicad_mod
  fp-lib-table
Labels: Addition

#1789 Added footprint for OLED 128x64
  Display.pretty/OLED-128O064D.kicad_mod
Labels: Addition

#2369 Add Sensirion SHT3x-DIS DFN-8 package
  Sensor_Humidity.pretty/Sensirion_DFN-8-1EP_2.5x2.5mm_P0.5mm_EP1.1x1.7mm.kicad_mod
Labels: Addition

#2284 Added MicroChip DFN-8-1EP Dual Flat 8 Lead Package
  Package_DFN_QFN.pretty/DFN-8-1EP_3x2mm_P0.5mm_EP1.7x1.4mm.kicad_mod
Labels: Addition

#2355 Added D_DO-247-2_Vertical
  Diode_THT.pretty/D_DO-247_Horizontal_TabDown.kicad_mod
  Diode_THT.pretty/D_DO-247_Horizontal_TabUp.kicad_mod
  Diode_THT.pretty/D_DO-247_Vertical.kicad_mod
Labels: Addition, Pending changes

#2324 Fix reversed pin numbering
  Connector_RJ.pretty/RJ45_Molex_0855135013_Vertical.kicad_mod
Labels: Bug

#2328 Added IXYS GUFP footprint
  Diode_THT.pretty/Diode_Bridge_IXYS_GUFP.kicad_mod
Labels: Addition

#2361 UDFN2020-6_Type-F package added
  Package_DFN_QFN.pretty/Diodes_UDFN2020-6_Type-F.kicad_mod
Labels: Addition

#2379 Add HVSON-8-1EP_3x3mm_P0.65mm_EP1.6x2.4mm
  Package_SON.pretty/HVSON-8-1EP_3x3mm_P0.65mm_EP1.6x2.4mm.kicad_mod
Labels: Addition

#2384 Fix HVSON-8-1EP_3x3mm_P0.65mm_EP1.6x2.4mm datasheet URL
  Package_SON.pretty/HVSON-8-1EP_3x3mm_P0.65mm_EP1.6x2.4mm.kicad_mod
Labels: Enhancement

#2387 Fix typo in Molex and Multicomp description
  fp-lib-table
Labels: Bug

#2349 Fix issue #2348, added missing F.Paste for pad number 3
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-1.kicad_mod
Labels: Bug, Pending reviewer

#2396 TO-92: move F.Fab ref des under part body
  Package_TO_SOT_THT.pretty/Heraeus_TO-92-2.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92-2.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92-2_Wide.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92L.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92L_Inline.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92L_Inline_Wide.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92L_Wide.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92Mini-2.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92S-2.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92S.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92S_Wide.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92_HandSolder.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92_Inline.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92_Inline_Wide.kicad_mod
  Package_TO_SOT_THT.pretty/TO-92_Wide.kicad_mod
Labels: Bug

#2398 More accurate description for D_MiniMELF
  Diode_SMD.pretty/D_MiniMELF.kicad_mod
  Diode_SMD.pretty/D_MiniMELF_Handsoldering.kicad_mod
Labels: Enhancement, Pending reviewer

#2334 Add TDFN-8_1EP-3x2mm_P0.5mm_EP1.3x1.4mm
  Package_DFN_QFN.pretty/TDFN-8-1EP_3x2mm_P0.5mm_EP1.3x1.4mm.kicad_mod
Labels: Addition

#2409 So 14
  Package_SO.pretty/SO-14_3.9x8.65mm_P1.27mm.kicad_mod
Labels: Addition

#2386 Added Transformer_Wuerth_750315371
  Transformer_SMD.pretty/Transformer_Wuerth_750315371.kicad_mod
Labels: Addition, Pending changes

#2194 Add HVQFN-16-1EP_3x3mm_P0.5mm_EP1.5x1.5mm.
  Package_DFN_QFN.pretty/HVQFN-16-1EP_3x3mm_P0.5mm_EP1.5x1.5mm.kicad_mod
Labels: Addition

#2195 Add SO-16_3.9x9.9mm_P1.27mm.
  Package_SO.pretty/SO-16_3.9x9.9mm_P1.27mm.kicad_mod
Labels: Addition, Pending changes

#2175 Add longer SIP9 package (based on existing SIP-9_21.54x3mm_P2.54mm)
  Package_SIP.pretty/SIP-9_22.3x3mm_P2.54mm.kicad_mod
Labels: Addition

#2352 Added Converter_ACDC_MeanWell_IRM-60-xx_THT
  Converter_ACDC.pretty/Converter_ACDC_MeanWell_IRM-60-xx_THT.kicad_mod
Labels: Addition

#2298 Create SOIC-14-16_3.9x9.9mm_P1.27mm.kicad_mod
  Package_SO.pretty/SOIC-14-16_3.9x9.9mm_P1.27mm.kicad_mod
Labels: Addition

#2413 Fix LED_D5.0mm-4_RGB_Staggered_Pins datasheet link
  LED_THT.pretty/LED_D5.0mm-4_RGB_Staggered_Pins.kicad_mod
Labels: Enhancement

#2367 Add DFN-8-1EP_2x2mm_P0.5mm_EP0.6x1.2mm used for the SGL0622Z
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.6x1.2mm.kicad_mod
Labels: Addition

#2327 Add Würth WE-GF inductor
  Inductor_SMD.pretty/L_Wuerth_WE-GF-1210.kicad_mod
Labels: Addition

#2425 Bugfix: Buzzer_Beeper.pretty/MagneticBuzzer_Kobitone_254-EMB84Q-RO
  Buzzer_Beeper.pretty/MagneticBuzzer_Kobitone_254-EMB84Q-RO.kicad_mod
Labels: Bug

#2428 Remove Legacy README.md in Button_Switch_Keyboard
  Button_Switch_Keyboard.pretty/README.md
Labels: Enhancement

#2382 Added footprint for ADE7953
  Package_CSP.pretty/LFCSP-28-1EP_5x5mm_P0.5mm_EP3.14x3.14mm.kicad_mod
  Package_CSP.pretty/LFCSP-28-1EP_5x5mm_P0.5mm_EP3.14x3.14mm_ThermalVias.kicad_mod
Labels: Addition

#2213 Create Diode_Bridge_Vishay_KBPM.kicad_mod
  Diode_THT.pretty/Diode_Bridge_Vishay_KBPM.kicad_mod
Labels: Addition

#1958 Create LEM_CKSR.kicad_mod
  Sensor_Current.pretty/LEM_CKSR.kicad_mod
Labels: Addition, Ready for review

#2312 Add DFN-8 for Linear LTC2451
  Package_DFN_QFN.pretty/DFN-8-1EP_2x3mm_P0.5mm_EP0.56x2.15mm.kicad_mod
Labels: Addition

#2318 Add TSSOP-4_4.4x5.0mm_P4.0mm for Onsemi MDBxxS Bridge Rectifier
  Package_SO.pretty/TSSOP-4_4.4x5mm_P4mm.kicad_mod
Labels: Addition

#2201 Added CUI CUI_CMC-4013-SMT SMD microphone
  Sensor_Audio.pretty/CUI_CMC-4013-SMT.kicad_mod
Labels: Addition, Pending changes

#2427 Added SOP-20 for HT12D
  Package_SO.pretty/SOP-20_7.06x12.8mm_P1.27mm.kicad_mod
Labels: Addition

#2426 add SOP_16_3.9x9.9mm_P1.27mm
  Package_SO.pretty/SOP-16_3.9x9.9mm_P1.27mm.kicad_mod
Labels: Addition

#2443 Bugfix: Position of lower mounting hole was wrong
  Battery.pretty/BatteryHolder_Eagle_12BH611-GR.kicad_mod
Labels: Bug

#2188 added VFBGA-86 footprint for DA14691 and DA14695 MCU
  Package_BGA.pretty/VFBGA-86_6x6mm_Layout10x10_P0.55mm_Ball0.25mm_Pad0.2mm.kicad_mod
Labels: Addition, Scripting required
