Repository KiCad/kicad-footprints, pull requests merged in 2020-05, with the labels that each got.

#2248 Added TDFN 10 Package with Exposed pad
  Package_DFN_QFN.pretty/TDFN-10-1EP_2x3mm_P0.5mm_EP0.9x2mm.kicad_mod
  Package_DFN_QFN.pretty/TDFN-10-1EP_2x3mm_P0.5mm_EP0.9x2mm_ThermalVias.kicad_mod
Labels: Addition

#2207 Added WQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm
  Package_DFN_QFN.pretty/WQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
Labels: Addition

#2196 Mini-Circuits footprint HQ1157
  RF_Mini-Circuits.pretty/Mini-Circuits_HQ1157.kicad_mod
Labels: Addition

#2253 Add Analog LFCSP-WD-8
  Package_CSP.pretty/LFCSP-WD-8-1EP_3x3mm_P0.65mm_EP1.6x2.44mm.kicad_mod
  Package_CSP.pretty/LFCSP-WD-8-1EP_3x3mm_P0.65mm_EP1.6x2.44mm_ThermalVias.kicad_mod
Labels: Addition

#2260 Package SO: Create HTTSOP package for TPS2663xPWP
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.96x2.96mm.kicad_mod
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.96x2.96mm_ThermalVias.kicad_mod
Labels: Addition

#2230 Add Kemet Ex2 Series Mechanical Relays
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NU.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NUH.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NUH_DoubleCoil.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NUX_DoubleCoil.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NUX_NKX.kicad_mod
  Relay_SMD.pretty/Relay_DPDT_Kemet_EE2_NU_DoubleCoil.kicad_mod
  Relay_THT.pretty/Relay_DPDT_Kemet_EC2.kicad_mod
  Relay_THT.pretty/Relay_DPDT_Kemet_EC2_DoubleCoil.kicad_mod
Labels: Addition, Pending changes

#2261 Common mode choke Wuerth WE-SL5
  Inductor_SMD.pretty/L_CommonModeChoke_Wuerth_WE-SL5.kicad_mod
Labels: Addition

#2262 Common mode chokes Coilcraft
  Inductor_SMD.pretty/L_CommonModeChoke_Coilcraft_0603USB.kicad_mod
  Inductor_SMD.pretty/L_CommonModeChoke_Coilcraft_0805USB.kicad_mod
  Inductor_SMD.pretty/L_CommonModeChoke_Coilcraft_1812CAN.kicad_mod
Labels: Addition

#2266 Added bevel to corner of package on FAB layer. Bevel is 1mm. (1.414mm…
  Package_SO.pretty/PowerPAK_SO-8_Dual.kicad_mod
  Package_SO.pretty/PowerPAK_SO-8_Single.kicad_mod
Labels: Bug

#2167 Re-submit TDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.2mm package for MAX17620
  Package_DFN_QFN.pretty/TDFN-8-1EP_2x2mm_P0.5mm_EP0.8x1.2mm.kicad_mod
Labels: Addition

#2254 Added WDFN-8-1EP_4x3mm_P0.65mm_EP2.4x1.8mm (script generated)
  Package_DFN_QFN.pretty/WDFN-8-1EP_4x3mm_P0.65mm_EP2.4x1.8mm.kicad_mod
  Package_DFN_QFN.pretty/WDFN-8-1EP_4x3mm_P0.65mm_EP2.4x1.8mm_ThermalVias.kicad_mod
Labels: Addition

#2273 Add DFN-6-1EP_2x2mm_P0.5mm_EP0.6x1.37mm
  Package_DFN_QFN.pretty/DFN-6-1EP_2x2mm_P0.5mm_EP0.6x1.37mm.kicad_mod
Labels: Addition

#2060 Add HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm
  Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm.kicad_mod
  Package_DFN_QFN.pretty/HVQFN-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias.kicad_mod
Labels: Addition

#1704 Infineon hsof-8-1 update, hsof-8-2 add
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-1.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-1_ThermalVias.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-2.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-2_ThermalVias.kicad_mod
  Package_TO_SOT_SMD.pretty/Infineon_PG-HSOF-8-2_ThermalVias2.kicad_mod
Labels: Bug, Enhancement

#1933 SD kyocera 145638109* fixed
  Connector_Card.pretty/SD_Kyocera_145638009211859+.kicad_mod
  Connector_Card.pretty/SD_Kyocera_145638009511859+.kicad_mod
  Connector_Card.pretty/SD_Kyocera_145638109211859+.kicad_mod
  Connector_Card.pretty/SD_Kyocera_145638109511859+.kicad_mod
Labels: Bug, Enhancement

#2057 Keystone 2479 Fix: Vertical distance from pin 1 center to top F.Fab line and component length are not correct.
  Battery.pretty/BatteryHolder_Keystone_2479_3xAAA.kicad_mod
Labels: Bug

#2263 Add LFCSP-16 1.3x1.3mm EP
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.3x1.3mm.kicad_mod
  Package_CSP.pretty/LFCSP-16-1EP_3x3mm_P0.5mm_EP1.3x1.3mm_ThermalVias.kicad_mod
Labels: Addition

#2211 Connector JAE: Add Nano SIM Card SF72S006
  Connector_JAE.pretty/JAE_SIM_Card_SF72S006.kicad_mod
Labels: Addition

#1951 Fix Vishay-MBLS pin order
  Diode_SMD.pretty/Diode_Bridge_Vishay_MBLS.kicad_mod
Labels: Bug

#2208 Added QFN-56 5.9x5.9EP
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP5.9x5.9mm_ThermalVias.kicad_mod
Labels: Addition, Pending changes

#2158 ESP32-S2-WROVER: Added keepout on DWGS layer for espressif recommende…
  RF_Module.pretty/ESP32-S2-WROVER.kicad_mod
Labels: Enhancement

#2069 Fix TC2050-IDC-NL courtyard and added front silkscreen.
  Connector.pretty/Tag-Connect_TC2050-IDC-NL_2x05_P1.27mm_Vertical.kicad_mod
Labels: Bug

#1893 add SMD Fuse Schurter UMZ250
  Fuse.pretty/Fuse_Schurter_UMZ250.kicad_mod
Labels: Addition

#2234 Added footprint for CUI CMR-12062S-67 speaker
  Buzzer_Beeper.pretty/Speaker_CUI_CMR-1206S-67.kicad_mod
Labels: Addition

#1770 add SMA connector Molex 73251-2120
  Connector_Coaxial.pretty/SMA_Molex_73251-2120_EdgeMount_Horizontal.kicad_mod
Labels: Addition

#2070 Added TC2050-IDC-NL with bottom courtyard for TC2050-NL clip board.
  Connector.pretty/Tag-Connect_TC2050-IDC-NL_2x05_P1.27mm_Vertical_with_bottom_clip.kicad_mod
Labels: Addition
