Repository KiCad/kicad-footprints, pull requests merged in 2020-01, with the labels that each got.

#1889 add Alps SKRTLAE010 horizontal push button
  Button_Switch_SMD.pretty/SW_Push_1P1T-MP_NO_Horizontal_Alps_SKRTLAE010.kicad_mod
Labels: Addition

#2033 Adding ST_uTFBGA-36_3.6x3.6mm_Layout6x6_P0.5mm
  Package_BGA.pretty/ST_uTFBGA-36_3.6x3.6mm_Layout6x6_P0.5mm.kicad_mod
Labels: Addition, Pending reviewer

#2026 Adding QFN-56-1EP_8x8mm_P0.5mm_EP4.3x4.3mm
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.3x4.3mm.kicad_mod
  Package_DFN_QFN.pretty/QFN-56-1EP_8x8mm_P0.5mm_EP4.3x4.3mm_ThermalVias.kicad_mod
Labels: Addition, Pending reviewer

#1946 Add DFN-4
  Sensor_Humidity.pretty/Sensirion_DFN-4-1EP_2x2mm_P1mm_EP0.7x1.6mm.kicad_mod
  fp-lib-table
Labels: Addition, Ready for review

#1722 Fischer FK224 ... 220 1 heatsink
  Heatsink.pretty/Heatsink_Fischer_FK224xx2201_25x8.3mm.kicad_mod
Labels: Addition, Ready for review

#1547 add scripted SO-20 Texas PowerPAD
  Package_SO.pretty/SO-20-1EP_7.52x12.825mm_P1.27mm_EP6.045x12.09mm_Mask3.56x4.47mm.kicad_mod
  Package_SO.pretty/SO-20-1EP_7.52x12.825mm_P1.27mm_EP6.045x12.09mm_Mask3.56x4.47mm_ThermalVias.kicad_mod
Labels: Addition, Ready for review

#1576 Adding footprint for relay Fujitsu FTR-B3S.
  Relay_SMD.pretty/Relay_Fujitsu_FTR-B3S.kicad_mod
Labels: Addition, Pending changes

#1469 Battery: Add the 6.8mm Keystone 2998 coin cell holder
  Battery.pretty/BatteryHolder_Keystone_2998_1x6.8mm.kicad_mod
Labels: Addition, Pending changes

#2030 Add USB_C_Receptacle_XKB_U262-161N-4BVC11
  Connector_USB.pretty/USB_C_Receptacle_XKB_U262-16XN-4BVC11.kicad_mod
Labels: Addition, Pending reviewer

#1702 Sot 89 custom pads
  Package_TO_SOT_SMD.pretty/SOT-89-3.kicad_mod
  Package_TO_SOT_SMD.pretty/SOT-89-3_Handsoldering.kicad_mod
  Package_TO_SOT_SMD.pretty/SOT-89-5.kicad_mod
  Package_TO_SOT_SMD.pretty/SOT-89-5_Handsoldering.kicad_mod
Labels: Enhancement, Pending reviewer

#1773 Add RF Testpoint MS-156C3
  Connector_Coaxial.pretty/CoaxialSwitch_Hirose_MS-156C3_Horizontal.kicad_mod
Labels: Addition, Pending changes

#2036 Add missing non thermal vias footprint for LMZM23601
  Package_LGA.pretty/Texas_SIL0010A_MicroSiP-10-1EP_3.8x3mm_P0.6mm_EP0.7x2.9mm.kicad_mod
Labels: Bug, Pending reviewer

#1910 Fix EP radius and resync of LGA footprints
  Package_LGA.pretty/Bosch_LGA-8_3x3mm_P0.8mm_ClockwisePinNumbering.kicad_mod
  Package_LGA.pretty/LGA-14_2x2mm_P0.35mm_LayoutBorder3x4y.kicad_mod
  Package_LGA.pretty/LGA-14_3x2.5mm_P0.5mm_LayoutBorder3x4y.kicad_mod
  Package_LGA.pretty/LGA-14_3x5mm_P0.8mm_LayoutBorder1x6y.kicad_mod
  Package_LGA.pretty/LGA-16_3x3mm_P0.5mm_LayoutBorder3x5y.kicad_mod
  Package_LGA.pretty/LGA-16_4x4mm_P0.65mm_LayoutBorder4x4y.kicad_mod
  Package_LGA.pretty/NXP_LGA-8_3x5mm_P1.25mm_H1.1mm.kicad_mod
  Package_LGA.pretty/NXP_LGA-8_3x5mm_P1.25mm_H1.2mm.kicad_mod
  Package_LGA.pretty/ST_HLGA-10_2.5x2.5mm_P0.6mm_LayoutBorder3x2y.kicad_mod
  Package_LGA.pretty/Texas_SIL0008D_MicroSiP-8-1EP_2.8x3mm_P0.65mm_EP1.1x1.9mm.kicad_mod
  Package_LGA.pretty/Texas_SIL0008D_MicroSiP-8-1EP_2.8x3mm_P0.65mm_EP1.1x1.9mm_ThermalVias.kicad_mod
  Package_LGA.pretty/Texas_SIL0010A_MicroSiP-10-1EP_3.8x3mm_P0.6mm_EP0.7x2.9mm_ThermalVias.kicad_mod
Labels: Bug, Enhancement, Pending reviewer

#2037 Add missing scripted variants of SO packages
  Package_SO.pretty/HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3.4x5mm_Mask2.46x2.31mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.68x1.88mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1907 Package_SO fix EP round radius
  Package_SO.pretty/HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.1mm.kicad_mod
  Package_SO.pretty/HSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.1mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.4x3.2mm.kicad_mod
  Package_SO.pretty/HTSOP-8-1EP_3.9x4.9mm_P1.27mm_EP2.4x3.2mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3.4x5mm_Mask2.46x2.31mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3x3mm.kicad_mod
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.4x3.7mm.kicad_mod
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.75x3.43mm.kicad_mod
  Package_SO.pretty/HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.75x3.43mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSSOP-24-1EP_4.4x7.8mm_P0.65mm_EP3.2x5mm.kicad_mod
  Package_SO.pretty/HTSSOP-24-1EP_4.4x7.8mm_P0.65mm_EP3.4x7.8mm_Mask2.4x4.68mm.kicad_mod
  Package_SO.pretty/HTSSOP-24-1EP_4.4x7.8mm_P0.65mm_EP3.4x7.8mm_Mask2.4x4.68mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSSOP-28-1EP_4.4x9.7mm_P0.65mm_EP2.85x5.4mm.kicad_mod
  Package_SO.pretty/HTSSOP-28-1EP_4.4x9.7mm_P0.65mm_EP2.85x5.4mm_ThermalVias.kicad_mod
  Package_SO.pretty/HTSSOP-38-1EP_6.1x12.5mm_P0.65mm_EP5.2x12.5mm_Mask3.39x6.35mm.kicad_mod
  Package_SO.pretty/HTSSOP-38-1EP_6.1x12.5mm_P0.65mm_EP5.2x12.5mm_Mask3.39x6.35mm_ThermalVias.kicad_mod
  Package_SO.pretty/Infineon_PG-DSO-8-27_3.9x4.9mm_EP2.65x3mm.kicad_mod
  Package_SO.pretty/Infineon_PG-DSO-8-27_3.9x4.9mm_EP2.65x3mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.68x1.88mm.kicad_mod
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.68x1.88mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.73x1.98mm.kicad_mod
  Package_SO.pretty/MSOP-10-1EP_3x3mm_P0.5mm_EP1.73x1.98mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-12-1EP_3x4mm_P0.65mm_EP1.65x2.85mm.kicad_mod
  Package_SO.pretty/MSOP-12-1EP_3x4mm_P0.65mm_EP1.65x2.85mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm.kicad_mod
  Package_SO.pretty/MSOP-16-1EP_3x4.039mm_P0.5mm_EP1.651x2.845mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.68x1.88mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.73x1.85mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.73x1.85mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.95x2.15mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP1.95x2.15mm_ThermalVias.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.5x3mm_Mask1.73x2.36mm.kicad_mod
  Package_SO.pretty/MSOP-8-1EP_3x3mm_P0.65mm_EP2.5x3mm_Mask1.73x2.36mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.29x3mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.29x3mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.81mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.81mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.514x3.2mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.514x3.2mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.95x4.9mm_Mask2.71x3.4mm.kicad_mod
  Package_SO.pretty/SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.95x4.9mm_Mask2.71x3.4mm_ThermalVias.kicad_mod
  Package_SO.pretty/SOP-8-1EP_4.57x4.57mm_P1.27mm_EP4.57x4.45mm.kicad_mod
  Package_SO.pretty/SOP-8-1EP_4.57x4.57mm_P1.27mm_EP4.57x4.45mm_ThermalVias.kicad_mod
  Package_SO.pretty/Texas_R-PDSO-G8_EP2.95x4.9mm_Mask2.4x3.1mm.kicad_mod
  Package_SO.pretty/Texas_R-PDSO-G8_EP2.95x4.9mm_Mask2.4x3.1mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#1912 Fix EP round radius for TI QFN footpirnts
  Package_DFN_QFN.pretty/Texas_R-PWQFN-N28_EP2.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_R-PWQFN-N28_EP2.1x3.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024C_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024C_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024H_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGE0024H_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_RUM0016A_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_RUM0016A_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N16_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N16_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.4x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP3.15x3.15mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N20_EP3.15x3.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N24_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N24_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N32_EP3.45x3.45mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N32_EP3.45x3.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N36_EP4.4x4.4mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N36_EP4.4x4.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP2.9x2.9mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP2.9x2.9mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP3.52x2.62mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP3.52x2.62mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP4.15x4.15mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP4.15x4.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP4.6x4.6mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N40_EP4.6x4.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N48_EP5.15x5.15mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N48_EP5.15x5.15mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N64_EP4.25x4.25mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PVQFN-N64_EP4.25x4.25mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N16_EP2.1x2.1mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N16_EP2.1x2.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N24_EP2.7x2.7mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N24_EP2.7x2.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N32_EP2.8x2.8mm.kicad_mod
  Package_DFN_QFN.pretty/Texas_S-PWQFN-N32_EP2.8x2.8mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/Texas_X2QFN-12_1.6x1.6mm_P0.4mm.kicad_mod
Labels: Bug, Pending reviewer

#1915 Fix EP round radius for xQFN footprints
  Package_DFN_QFN.pretty/TQFN-16-1EP_3x3mm_P0.5mm_EP1.23x1.23mm.kicad_mod
  Package_DFN_QFN.pretty/TQFN-16-1EP_5x5mm_P0.8mm_EP3.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/TQFN-20-1EP_5x5mm_P0.65mm_EP3.1x3.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/TQFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_PullBack.kicad_mod
  Package_DFN_QFN.pretty/TQFN-24-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_PullBack_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-10_1.3x1.8mm_P0.4mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-10_1.6x2.1mm_P0.5mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-16-1EP_4x4mm_P0.65mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-16-1EP_4x4mm_P0.65mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-20-1EP_3x3mm_P0.4mm_EP1.85x1.85mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-20-1EP_3x3mm_P0.4mm_EP1.85x1.85mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-20-1EP_4x4mm_P0.5mm_EP2.8x2.8mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-20-1EP_4x4mm_P0.5mm_EP2.8x2.8mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-28-1EP_4x4mm_P0.4mm_EP2.35x2.35mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-28-1EP_4x4mm_P0.4mm_EP2.35x2.35mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-40-1EP_5x5mm_P0.4mm_EP3.8x3.8mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-40-1EP_5x5mm_P0.4mm_EP3.8x3.8mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-48-1EP_6x6mm_P0.4mm_EP4.45x4.45mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-48-1EP_6x6mm_P0.4mm_EP4.45x4.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/UQFN-48-1EP_6x6mm_P0.4mm_EP4.62x4.62mm.kicad_mod
  Package_DFN_QFN.pretty/UQFN-48-1EP_6x6mm_P0.4mm_EP4.62x4.62mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.45x1.45mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.45x1.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.8x1.8mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-16-1EP_3x3mm_P0.5mm_EP1.8x1.8mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.45mm_EP1.55x1.55mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.45mm_EP1.55x1.55mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-20-1EP_3x3mm_P0.4mm_EP1.7x1.7mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-28-1EP_4x4mm_P0.45mm_EP2.4x2.4mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-28-1EP_4x4mm_P0.45mm_EP2.4x2.4mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-28-1EP_4x5mm_P0.5mm_EP2.55x3.55mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-28-1EP_4x5mm_P0.5mm_EP2.55x3.55mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm.kicad_mod
  Package_DFN_QFN.pretty/VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-14-1EP_2.5x2.5mm_P0.5mm_EP1.45x1.45mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-14-1EP_2.5x2.5mm_P0.5mm_EP1.45x1.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_3x3mm_P0.5mm_EP1.75x1.75mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_3x3mm_P0.5mm_EP1.75x1.75mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-16-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm_ThermalVias.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm.kicad_mod
  Package_DFN_QFN.pretty/WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm_ThermalVias.kicad_mod
Labels: Bug, Pending reviewer

#2035 Remove wrongly added qfn (manufactuer specific one is in RF lib)
  Package_DFN_QFN.pretty/QFN-14-1EP_1.6x1.6mm_P0.4mm_EP0.74x0.74mm.kicad_mod
Labels: Bug, Pending reviewer

#1696 Add Murata MEE isolated DC/DC SIP footprints
  Converter_DCDC.pretty/Converter_DCDC_Murata_MEE1SxxxxSC_THT.kicad_mod
  Converter_DCDC.pretty/Converter_DCDC_Murata_MEE3SxxxxSC_THT.kicad_mod
Labels: Addition, Pending changes

#1978 Create Diodes U-DFN2510-10 footprint
  Package_DFN_QFN.pretty/Diodes_UDFN-10_1.0x2.5mm_P0.5mm.kicad_mod
Labels: Addition, Pending changes

#2027 Added SOT-523 footprint, modified from SOT-553
  Package_TO_SOT_SMD.pretty/SOT-523.kicad_mod
Labels: Addition, Pending changes

#2012 Added WSON-10-1EP_2.5x2.5mm_P0.5mm_EP1.2x2mm.
  Package_SON.pretty/WSON-10-1EP_2.5x2.5mm_P0.5mm_EP1.2x2mm.kicad_mod
  Package_SON.pretty/WSON-10-1EP_2.5x2.5mm_P0.5mm_EP1.2x2mm_ThermalVias.kicad_mod
Labels: Addition

#2004 Added footprint for DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm.
  Package_DFN_QFN.pretty/DFN-8-1EP_2x2mm_P0.5mm_EP0.7x1.3mm.kicad_mod
Labels: Addition
